/* Lueri Careers — seven-language localization layer
 * Canonical recruitment data stays in Supabase; this layer localizes the public UI
 * and the currently defined role catalogue without changing the stored English record.
 */
(function(){
  'use strict';
  var LOCALES=['en','zh','sw','fr','es','ar','pt'];
  var ROLE_KEYS={
    'Dispatch & Operations Coordinator':'dispatch',
    'Customer Support Representative':'support',
    'Business Development Representative':'sales',
    'General / Future Opportunity':'future'
  };
  var T={
    en:{
      meta:{title:'Careers — Lueri International',description:'Current jobs and careers at Lueri International in Nairobi — operations, customer experience, sales, and future opportunities.'},
      nav:{where:'Where to next',services:'Services',servicesCaption:'What we carry, and how fast',pricing:'Pricing',pricingCaption:'Quoted rates, no hidden fees',business:'Business',businessCaption:'Set up a corporate account',coverage:'Coverage',coverageCaption:'Where we deliver in Nairobi',why:'Why Us',whyCaption:'What makes Lueri different',faq:'FAQ',faqCaption:'Common questions, answered',rewards:'Rewards',rewardsCaption:'Earn points on every delivery',careers:'Careers',careersCaption:'Future roles at Lueri',book:'Book',bookCaption:'Send a pickup request now',menu:'Menu',close:'Close',bookPickup:'Book Pickup',theme:'Toggle dark mode',languageSelect:'Select language'},
      hero:{eyebrow:'People / Careers',form:'FORM NO. HR–2026',title:'BUILD THE<br>NETWORK.<br>MOVE WITH US.',subtitle:"This is Lueri International's recruitment desk. See genuine open positions, read the role requirements, and apply directly. Corporate accounts belong on the Business page.",open:'View open roles',future:'Future opportunities'},
      roles:{heading:'Open positions',loading:'Loading current openings…',emptyTitle:'No current openings',emptyText:'Lueri does not have a confirmed public vacancy at this time. New positions will appear here when recruitment opens.',unavailable:'Openings are temporarily unavailable<br>Please try again shortly. The application system is still protected and no application data has been submitted.',whatDo:'What you’ll do',fallback:'See the role details below.',lookFor:'What we look for',apply:'View role & apply',futureOption:'Future opportunity / talent pool'},
      values:{heading:'What we look for',ownership:'Ownership',ownershipText:'Follow work through, communicate early when something is blocked, and take responsibility for the outcome.',customer:'Customer discipline',customerText:'Be clear, calm and useful when a customer is in a hurry or a delivery has gone off-plan.',accuracy:'Operational accuracy',accuracyText:'Addresses, phone numbers, delivery status and handover records need careful handling.',learning:'Learning speed',learningText:'We use technology and automation aggressively. The ability to learn new workflows and tools matters.'},
      future:{heading:'Future opportunities',text:'No current vacancy fits? You can still submit your details for future recruitment in operations, customer experience, sales, technology, finance or administration.',join:'Join the talent pool'},
      form:{heading:'Apply',role:'Role',roleLoading:'Loading roles…',roleSelect:'Select a role…',name:'Full Name',phone:'Phone',phonePlaceholder:'07xx xxx xxx',email:'Email',location:'Location',locationPlaceholder:'e.g. Nairobi',summary:'Relevant experience / why you’re a fit',summaryPlaceholder:'Briefly describe your relevant experience, skills, availability and what you would bring to Lueri.',cv:'CV / Portfolio Link',linkedin:'LinkedIn (optional)',availability:'Availability (optional)',availabilityPlaceholder:'e.g. Immediately / 30 days',salary:'Expected salary (optional)',salaryPlaceholder:'Optional',submit:'Submit application',privacy:'We only request information needed for recruitment. Do not submit passwords, KRA PINs, national ID numbers, bank details or other sensitive identity documents at this stage.'},
      messages:{roleRequired:'Please select the role you are applying for.',name:'Please enter your full name.',phone:'Please enter a valid Kenyan phone number.',email:'Please enter a valid email address.',summary:'Please provide at least a short summary of your relevant experience.',cv:'Your CV / portfolio link must start with https:// or http://.',linkedin:'Your LinkedIn link must start with https:// or http://.',roleUnavailable:'That role is no longer accepting applications. Please refresh the page and choose another role.',invalidName:'Please enter a valid full name.',invalidEmail:'Please enter a valid email address.',invalidPhone:'Please enter a valid phone number.',invalidSummary:'Please provide a little more information about your experience and fit.',invalidCv:'Please check your CV / portfolio link.',invalidLinkedin:'Please check your LinkedIn link.',duplicate:'We already received an application from this email for this role in the last 24 hours.',rate:'Too many application attempts were made from this connection. Please try again later.',submitFailed:'We could not submit the application. Please try again.',received:'Application received. Lueri has recorded your application for {role}. Keep your phone and email available in case the recruitment team contacts you.',system:'Recruitment service unavailable.',unavailableTitle:'Openings are temporarily unavailable',submitted:'Submitting…'},
      rolesData:{
        dispatch:{title:'Dispatch & Operations Coordinator',department:'Operations',location:'Nairobi, Kenya',type:'Full-time',summary:'Coordinate pickups, dispatch, delivery exceptions and proof-of-delivery workflows.',description:'Own the operational flow from pickup request through successful handover, keeping dispatch information accurate and customers informed.',responsibilities:['Dispatch planning','Customer communication','Escalation handling','Delivery tracking','Daily reporting'],requirements:['Strong organisation and follow-through','Clear written and spoken communication','Comfort with CRM and messaging tools','Ability to work in a fast-moving delivery environment']},
        support:{title:'Customer Support Representative',department:'Customer Experience',location:'Nairobi, Kenya',type:'Full-time / Contract',summary:'Own customer conversations across WhatsApp, phone, email and digital channels.',description:'Help customers from booking through delivery, resolve issues quickly, and keep customer records accurate.',responsibilities:['Customer support','Issue resolution','Booking assistance','CRM updates','Service follow-up'],requirements:['Strong customer-service communication','Calm problem solving','Accurate record keeping','Comfort with digital support tools']},
        sales:{title:'Business Development Representative',department:'Sales & Business Development',location:'Nairobi, Kenya',type:'Full-time / Commission',summary:'Build Lueri’s B2B pipeline by developing relationships with businesses that need recurring delivery support.',description:'Identify qualified prospects, start commercial conversations, manage follow-up and hand qualified opportunities to account management.',responsibilities:['Prospecting','Outreach','Lead qualification','Meeting generation','Pipeline follow-up'],requirements:['Commercial communication skills','Persistence and disciplined follow-up','Interest in B2B sales','Ability to understand customer needs']},
        future:{title:'General / Future Opportunity',department:'Talent Pool',location:'Nairobi, Kenya',type:'Future opportunity',summary:'Submit your CV for future recruitment opportunities at Lueri International.',description:'Use this route when there is no current vacancy that matches your experience but you would like Lueri to consider you for future recruitment.',responsibilities:['Future recruitment matching','Talent pool review'],requirements:['Clear communication','Relevant experience','Willingness to learn']}
      }
    }
  },
  T.es={
    meta:{title:'Empleo — Lueri International',description:'Vacantes y oportunidades profesionales actuales en Lueri International en Nairobi: operaciones, atención al cliente, ventas y futuras oportunidades.'},
    nav:{where:'¿Adónde ahora?',services:'Servicios',servicesCaption:'Qué transportamos y con qué rapidez',pricing:'Precios',pricingCaption:'Precios cotizados, sin cargos ocultos',business:'Empresas',businessCaption:'Configura una cuenta corporativa',coverage:'Cobertura',coverageCaption:'Dónde entregamos en Nairobi',why:'Por qué nosotros',whyCaption:'Qué hace diferente a Lueri',faq:'Preguntas frecuentes',faqCaption:'Preguntas comunes, respuestas',rewards:'Recompensas',rewardsCaption:'Gana puntos con cada entrega',careers:'Empleo',careersCaption:'Oportunidades en Lueri',book:'Reservar',bookCaption:'Envía una solicitud de recogida',menu:'Menú',close:'Cerrar',bookPickup:'Reservar recogida',theme:'Cambiar modo oscuro',languageSelect:'Seleccionar idioma'},
    hero:{eyebrow:'Personas / Empleo',form:'FORMULARIO HR–2026',title:'CONSTRUYE LA<br>RED.<br>MUÉVETE CON NOSOTROS.',subtitle:'Este es el centro de contratación de Lueri International. Consulta vacantes reales, revisa los requisitos y presenta tu candidatura directamente. Las cuentas corporativas pertenecen a la página Empresas.',open:'Ver vacantes',future:'Futuras oportunidades'},
    roles:{heading:'Vacantes abiertas',loading:'Cargando vacantes actuales…',emptyTitle:'No hay vacantes actuales',emptyText:'Lueri no tiene una vacante pública confirmada en este momento. Las nuevas posiciones aparecerán aquí cuando se abra la contratación.',unavailable:'Las vacantes no están disponibles temporalmente<br>Inténtalo de nuevo en unos instantes. El sistema de solicitudes sigue protegido y no se ha enviado ninguna solicitud.',whatDo:'Qué harás',fallback:'Consulta los detalles del puesto a continuación.',lookFor:'Lo que buscamos',apply:'Ver puesto y solicitar',futureOption:'Futura oportunidad / bolsa de talento'},
    values:{heading:'Lo que buscamos',ownership:'Responsabilidad',ownershipText:'Lleva el trabajo hasta el final, comunica pronto cuando algo esté bloqueado y asume la responsabilidad del resultado.',customer:'Disciplina con el cliente',customerText:'Sé claro, tranquilo y útil cuando un cliente tiene prisa o una entrega se desvía del plan.',accuracy:'Precisión operativa',accuracyText:'Las direcciones, teléfonos, estados de entrega y registros de entrega requieren cuidado.',learning:'Rapidez para aprender',learningText:'Usamos tecnología y automatización de forma intensiva. La capacidad de aprender nuevos procesos y herramientas es importante.'},
    future:{heading:'Futuras oportunidades',text:'¿Ninguna vacante actual encaja? Puedes enviar tus datos para futuras contrataciones en operaciones, atención al cliente, ventas, tecnología, finanzas o administración.',join:'Unirse a la bolsa de talento'},
    form:{heading:'Solicitar',role:'Puesto',roleLoading:'Cargando puestos…',roleSelect:'Selecciona un puesto…',name:'Nombre completo',phone:'Teléfono',phonePlaceholder:'07xx xxx xxx',email:'Correo electrónico',location:'Ubicación',locationPlaceholder:'p. ej., Nairobi',summary:'Experiencia relevante / por qué encajas',summaryPlaceholder:'Describe brevemente tu experiencia, habilidades, disponibilidad y lo que aportarías a Lueri.',cv:'Enlace al CV / portafolio',linkedin:'LinkedIn (opcional)',availability:'Disponibilidad (opcional)',availabilityPlaceholder:'p. ej., Inmediatamente / 30 días',salary:'Salario esperado (opcional)',salaryPlaceholder:'Opcional',submit:'Enviar candidatura',privacy:'Solo solicitamos la información necesaria para la contratación. No envíes contraseñas, PIN de KRA, números de identificación nacional, datos bancarios ni otros documentos de identidad sensibles en esta etapa.'},
    messages:{roleRequired:'Selecciona el puesto al que deseas postularte.',name:'Introduce tu nombre completo.',phone:'Introduce un número de teléfono keniano válido.',email:'Introduce una dirección de correo válida.',summary:'Proporciona al menos un breve resumen de tu experiencia relevante.',cv:'El enlace de tu CV / portafolio debe comenzar por https:// o http://.',linkedin:'El enlace de LinkedIn debe comenzar por https:// o http://.',roleUnavailable:'Ese puesto ya no acepta solicitudes. Actualiza la página y elige otro puesto.',invalidName:'Introduce un nombre completo válido.',invalidEmail:'Introduce una dirección de correo válida.',invalidPhone:'Introduce un número de teléfono válido.',invalidSummary:'Proporciona un poco más de información sobre tu experiencia y perfil.',invalidCv:'Comprueba el enlace de tu CV / portafolio.',invalidLinkedin:'Comprueba el enlace de LinkedIn.',duplicate:'Ya recibimos una candidatura de este correo para este puesto durante las últimas 24 horas.',rate:'Se realizaron demasiados intentos desde esta conexión. Inténtalo de nuevo más tarde.',submitFailed:'No pudimos enviar la candidatura. Inténtalo de nuevo.',received:'Candidatura recibida. Lueri ha registrado tu solicitud para {role}. Mantén disponible tu teléfono y correo por si el equipo de contratación se pone en contacto contigo.',system:'El servicio de contratación no está disponible.',unavailableTitle:'Las vacantes no están disponibles temporalmente',submitted:'Enviando…'},
    rolesData:{
      dispatch:{title:'Coordinador/a de Despacho y Operaciones',department:'Operaciones',location:'Nairobi, Kenia',type:'Tiempo completo',summary:'Coordina recogidas, despachos, incidencias de entrega y procesos de prueba de entrega.',responsibilities:['Planificación de despachos','Comunicación con clientes','Gestión de incidencias','Seguimiento de entregas','Informes diarios'],requirements:['Gran organización y seguimiento','Comunicación escrita y oral clara','Comodidad con CRM y herramientas de mensajería','Capacidad para trabajar en un entorno de entregas dinámico']},
      support:{title:'Representante de Atención al Cliente',department:'Experiencia del Cliente',location:'Nairobi, Kenia',type:'Tiempo completo / Contrato',summary:'Gestiona conversaciones con clientes por WhatsApp, teléfono, correo y canales digitales.',responsibilities:['Atención al cliente','Resolución de incidencias','Asistencia con reservas','Actualización del CRM','Seguimiento del servicio'],requirements:['Sólida comunicación de atención al cliente','Resolución tranquila de problemas','Registro preciso de información','Comodidad con herramientas digitales de soporte']},
      sales:{title:'Representante de Desarrollo de Negocio',department:'Ventas y Desarrollo de Negocio',location:'Nairobi, Kenia',type:'Tiempo completo / Comisión',summary:'Desarrolla el canal B2B de Lueri creando relaciones con empresas que necesitan entregas recurrentes.',responsibilities:['Prospección','Contacto comercial','Cualificación de leads','Generación de reuniones','Seguimiento del pipeline'],requirements:['Habilidades de comunicación comercial','Persistencia y seguimiento disciplinado','Interés por las ventas B2B','Capacidad para comprender las necesidades del cliente']},
      future:{title:'Oportunidad general / futura',department:'Bolsa de talento',location:'Nairobi, Kenia',type:'Futura oportunidad',summary:'Envía tu CV para futuras oportunidades de contratación en Lueri International.',responsibilities:['Búsqueda de oportunidades futuras','Revisión de la bolsa de talento'],requirements:['Comunicación clara','Experiencia relevante','Disposición para aprender']}
    }
  };
  T.fr={
    meta:{title:'Carrières — Lueri International',description:'Postes actuels et opportunités professionnelles chez Lueri International à Nairobi : opérations, expérience client, ventes et futures opportunités.'},
    nav:{where:'Où aller ensuite',services:'Services',servicesCaption:'Ce que nous transportons et à quelle vitesse',pricing:'Tarifs',pricingCaption:'Tarifs annoncés, sans frais cachés',business:'Entreprises',businessCaption:'Créer un compte entreprise',coverage:'Couverture',coverageCaption:'Où nous livrons à Nairobi',why:'Pourquoi nous',whyCaption:'Ce qui distingue Lueri',faq:'FAQ',faqCaption:'Questions fréquentes, réponses',rewards:'Récompenses',rewardsCaption:'Gagnez des points à chaque livraison',careers:'Carrières',careersCaption:'Postes chez Lueri',book:'Réserver',bookCaption:'Envoyer une demande de collecte',menu:'Menu',close:'Fermer',bookPickup:'Réserver une collecte',theme:'Activer le mode sombre',languageSelect:'Choisir la langue'},
    hero:{eyebrow:'Personnes / Carrières',form:'FORMULAIRE HR–2026',title:'CONSTRUISEZ LE<br>RÉSEAU.<br>AVANCEZ AVEC NOUS.',subtitle:'Voici le bureau de recrutement de Lueri International. Consultez les postes réellement ouverts, leurs exigences et postulez directement. Les comptes entreprises sont gérés sur la page Entreprises.',open:'Voir les postes ouverts',future:'Futures opportunités'},
    roles:{heading:'Postes ouverts',loading:'Chargement des postes actuels…',emptyTitle:'Aucun poste actuellement ouvert',emptyText:'Lueri n’a pas de vacance publique confirmée pour le moment. Les nouveaux postes apparaîtront ici lorsque le recrutement ouvrira.',unavailable:'Les postes sont temporairement indisponibles<br>Veuillez réessayer dans un instant. Le système de candidature reste protégé et aucune candidature n’a été envoyée.',whatDo:'Vos missions',fallback:'Consultez les détails du poste ci-dessous.',lookFor:'Profil recherché',apply:'Voir le poste et postuler',futureOption:'Future opportunité / vivier de talents'},
    values:{heading:'Ce que nous recherchons',ownership:'Responsabilité',ownershipText:'Allez au bout du travail, signalez rapidement les blocages et assumez la responsabilité du résultat.',customer:'Discipline client',customerText:'Soyez clair, calme et utile lorsqu’un client est pressé ou qu’une livraison dévie du plan.',accuracy:'Précision opérationnelle',accuracyText:'Les adresses, numéros de téléphone, statuts de livraison et preuves de remise exigent de la rigueur.',learning:'Rapidité d’apprentissage',learningText:'Nous utilisons fortement la technologie et l’automatisation. La capacité à apprendre de nouveaux processus et outils compte.'},
    future:{heading:'Futures opportunités',text:'Aucun poste actuel ne vous correspond ? Vous pouvez envoyer vos informations pour de futurs recrutements en opérations, expérience client, ventes, technologie, finance ou administration.',join:'Rejoindre le vivier de talents'},
    form:{heading:'Postuler',role:'Poste',roleLoading:'Chargement des postes…',roleSelect:'Sélectionnez un poste…',name:'Nom complet',phone:'Téléphone',phonePlaceholder:'07xx xxx xxx',email:'E-mail',location:'Lieu',locationPlaceholder:'ex. Nairobi',summary:'Expérience pertinente / pourquoi vous correspondez',summaryPlaceholder:'Décrivez brièvement votre expérience, vos compétences, votre disponibilité et ce que vous apporteriez à Lueri.',cv:'Lien CV / portfolio',linkedin:'LinkedIn (facultatif)',availability:'Disponibilité (facultatif)',availabilityPlaceholder:'ex. Immédiatement / 30 jours',salary:'Salaire souhaité (facultatif)',salaryPlaceholder:'Facultatif',submit:'Envoyer la candidature',privacy:'Nous demandons uniquement les informations nécessaires au recrutement. N’envoyez pas de mots de passe, PIN KRA, numéros d’identité nationale, coordonnées bancaires ou autres documents sensibles à ce stade.'},
    messages:{roleRequired:'Veuillez sélectionner le poste auquel vous postulez.',name:'Veuillez saisir votre nom complet.',phone:'Veuillez saisir un numéro de téléphone kenyan valide.',email:'Veuillez saisir une adresse e-mail valide.',summary:'Veuillez fournir au moins un bref résumé de votre expérience pertinente.',cv:'Le lien vers votre CV / portfolio doit commencer par https:// ou http://.',linkedin:'Le lien LinkedIn doit commencer par https:// ou http://.',roleUnavailable:'Ce poste n’accepte plus de candidatures. Actualisez la page et choisissez un autre poste.',invalidName:'Veuillez saisir un nom complet valide.',invalidEmail:'Veuillez saisir une adresse e-mail valide.',invalidPhone:'Veuillez saisir un numéro de téléphone valide.',invalidSummary:'Veuillez donner un peu plus d’informations sur votre expérience et votre profil.',invalidCv:'Veuillez vérifier le lien de votre CV / portfolio.',invalidLinkedin:'Veuillez vérifier votre lien LinkedIn.',duplicate:'Nous avons déjà reçu une candidature avec cet e-mail pour ce poste au cours des dernières 24 heures.',rate:'Trop de tentatives ont été effectuées depuis cette connexion. Veuillez réessayer plus tard.',submitFailed:'Nous n’avons pas pu envoyer la candidature. Veuillez réessayer.',received:'Candidature reçue. Lueri a enregistré votre candidature pour {role}. Gardez votre téléphone et votre e-mail disponibles au cas où l’équipe de recrutement vous contacterait.',system:'Le service de recrutement est indisponible.',unavailableTitle:'Les postes sont temporairement indisponibles',submitted:'Envoi…'}
  };
  T.sw={
    meta:{title:'Ajira — Lueri International',description:'Nafasi za kazi na fursa za ajira katika Lueri International Nairobi: operations, huduma kwa wateja, mauzo na fursa zijazo.'},
    nav:{where:'Tunaenda wapi sasa',services:'Huduma',servicesCaption:'Tunabeba nini na kwa kasi gani',pricing:'Bei',pricingCaption:'Bei wazi, bila gharama fiche',business:'Biashara',businessCaption:'Fungua akaunti ya kampuni',coverage:'Maeneo ya huduma',coverageCaption:'Tunapeleka wapi Nairobi',why:'Kwa nini sisi',whyCaption:'Kinachotofautisha Lueri',faq:'Maswali',faqCaption:'Maswali ya kawaida na majibu',rewards:'Rewards',rewardsCaption:'Pata pointi kwa kila delivery',careers:'Ajira',careersCaption:'Nafasi za kazi Lueri',book:'Agiza',bookCaption:'Tuma ombi la pickup',menu:'Menyu',close:'Funga',bookPickup:'Agiza Pickup',theme:'Badilisha hali ya giza',languageSelect:'Chagua lugha'},
    hero:{eyebrow:'Watu / Ajira',form:'FOMU HR–2026',title:'JENGA<br>MTANDAO.<br>SOGEA NASI.',subtitle:'Hii ni dawati la ajira la Lueri International. Angalia nafasi halisi zilizo wazi, soma mahitaji ya kazi na tuma maombi moja kwa moja. Akaunti za kampuni ziko kwenye ukurasa wa Biashara.',open:'Angalia nafasi zilizo wazi',future:'Fursa zijazo'},
    roles:{heading:'Nafasi zilizo wazi',loading:'Inapakia nafasi za sasa…',emptyTitle:'Hakuna nafasi zilizo wazi sasa',emptyText:'Lueri haina nafasi ya kazi ya umma iliyothibitishwa kwa sasa. Nafasi mpya zitaonekana hapa ajira zinapofunguliwa.',unavailable:'Nafasi hazipatikani kwa muda<br>Tafadhali jaribu tena baada ya muda mfupi. Mfumo wa maombi bado umelindwa na hakuna ombi limetumwa.',whatDo:'Utafanya nini',fallback:'Angalia maelezo ya nafasi hapa chini.',lookFor:'Tunatafuta nini',apply:'Angalia nafasi na tuma ombi',futureOption:'Fursa zijazo / talent pool'},
    values:{heading:'Tunatafuta nini',ownership:'Uwajibikaji',ownershipText:'Fuatilia kazi hadi mwisho, wasiliana mapema unapokwama na chukua jukumu la matokeo.',customer:'Nidhamu kwa mteja',customerText:'Kuwa wazi, mtulivu na mwenye msaada mteja akiwa na haraka au delivery ikitoka kwenye mpango.',accuracy:'Usahihi wa uendeshaji',accuracyText:'Anwani, nambari za simu, hali ya delivery na rekodi za makabidhiano zinahitaji umakini.',learning:'Kasi ya kujifunza',learningText:'Tunatumia teknolojia na automation kwa nguvu. Uwezo wa kujifunza workflows na zana mpya ni muhimu.'},
    future:{heading:'Fursa zijazo',text:'Hakuna nafasi ya sasa inayokufaa? Bado unaweza kutuma taarifa zako kwa ajira zijazo katika operations, huduma kwa wateja, mauzo, teknolojia, fedha au utawala.',join:'Jiunge na talent pool'},
    form:{heading:'Tuma ombi',role:'Nafasi',roleLoading:'Inapakia nafasi…',roleSelect:'Chagua nafasi…',name:'Jina kamili',phone:'Simu',phonePlaceholder:'07xx xxx xxx',email:'Barua pepe',location:'Mahali',locationPlaceholder:'mf. Nairobi',summary:'Uzoefu husika / kwa nini unafaa',summaryPlaceholder:'Eleza kwa ufupi uzoefu, ujuzi, upatikanaji na utakachoongeza Lueri.',cv:'Kiungo cha CV / portfolio',linkedin:'LinkedIn (si lazima)',availability:'Upatikanaji (si lazima)',availabilityPlaceholder:'mf. Mara moja / siku 30',salary:'Mshahara unaotarajiwa (si lazima)',salaryPlaceholder:'Si lazima',submit:'Tuma ombi',privacy:'Tunaomba tu taarifa zinazohitajika kwa ajira. Usitume nenosiri, PIN ya KRA, nambari ya kitambulisho, taarifa za benki au nyaraka nyingine nyeti za utambulisho kwa hatua hii.'},
    messages:{roleRequired:'Tafadhali chagua nafasi unayoomba.',name:'Tafadhali weka jina lako kamili.',phone:'Tafadhali weka nambari halali ya simu ya Kenya.',email:'Tafadhali weka barua pepe halali.',summary:'Tafadhali toa angalau muhtasari mfupi wa uzoefu wako husika.',cv:'Kiungo cha CV / portfolio lazima kianze na https:// au http://.',linkedin:'Kiungo cha LinkedIn lazima kianze na https:// au http://.',roleUnavailable:'Nafasi hiyo haipokei maombi tena. Refresh ukurasa na uchague nyingine.',invalidName:'Tafadhali weka jina kamili halali.',invalidEmail:'Tafadhali weka barua pepe halali.',invalidPhone:'Tafadhali weka nambari halali ya simu.',invalidSummary:'Tafadhali toa maelezo zaidi kuhusu uzoefu na uhalali wako.',invalidCv:'Tafadhali angalia kiungo cha CV / portfolio.',invalidLinkedin:'Tafadhali angalia kiungo cha LinkedIn.',duplicate:'Tayari tumepokea ombi kutoka kwa barua pepe hii kwa nafasi hii ndani ya saa 24 zilizopita.',rate:'Majaribio mengi yametoka kwenye muunganisho huu. Tafadhali jaribu baadaye.',submitFailed:'Hatukuweza kutuma ombi. Tafadhali jaribu tena.',received:'Ombi limepokelewa. Lueri imerekodi ombi lako la {role}. Weka simu na barua pepe yako tayari iwapo timu ya ajira itawasiliana nawe.',system:'Huduma ya ajira haipatikani.',unavailableTitle:'Nafasi hazipatikani kwa muda',submitted:'Inatuma…'}
  };
  T.pt={
    meta:{title:'Carreiras — Lueri International',description:'Vagas e oportunidades profissionais atuais na Lueri International em Nairobi: operações, experiência do cliente, vendas e futuras oportunidades.'},
    nav:{where:'Para onde agora',services:'Serviços',servicesCaption:'O que transportamos e com que rapidez',pricing:'Preços',pricingCaption:'Preços cotados, sem custos ocultos',business:'Empresas',businessCaption:'Criar uma conta empresarial',coverage:'Cobertura',coverageCaption:'Onde entregamos em Nairobi',why:'Por que nós',whyCaption:'O que diferencia a Lueri',faq:'FAQ',faqCaption:'Perguntas comuns, respostas',rewards:'Recompensas',rewardsCaption:'Ganhe pontos em cada entrega',careers:'Carreiras',careersCaption:'Vagas na Lueri',book:'Reservar',bookCaption:'Enviar um pedido de recolha',menu:'Menu',close:'Fechar',bookPickup:'Reservar recolha',theme:'Alternar modo escuro',languageSelect:'Selecionar idioma'},
    hero:{eyebrow:'Pessoas / Carreiras',form:'FORMULÁRIO HR–2026',title:'CONSTRUA A<br>REDE.<br>AVANCE CONNOSCO.',subtitle:'Este é o centro de recrutamento da Lueri International. Veja vagas reais, leia os requisitos e candidate-se diretamente. As contas empresariais pertencem à página Empresas.',open:'Ver vagas abertas',future:'Futuras oportunidades'},
    roles:{heading:'Vagas abertas',loading:'A carregar vagas atuais…',emptyTitle:'Não há vagas atuais',emptyText:'A Lueri não tem uma vaga pública confirmada neste momento. Novas posições aparecerão aqui quando o recrutamento abrir.',unavailable:'As vagas estão temporariamente indisponíveis<br>Tente novamente em instantes. O sistema de candidaturas continua protegido e nenhuma candidatura foi enviada.',whatDo:'O que fará',fallback:'Consulte os detalhes da vaga abaixo.',lookFor:'O que procuramos',apply:'Ver vaga e candidatar-se',futureOption:'Futura oportunidade / banco de talentos'},
    values:{heading:'O que procuramos',ownership:'Responsabilidade',ownershipText:'Leve o trabalho até ao fim, comunique cedo quando algo estiver bloqueado e assuma a responsabilidade pelo resultado.',customer:'Disciplina com o cliente',customerText:'Seja claro, calmo e útil quando um cliente está com pressa ou uma entrega sai do plano.',accuracy:'Precisão operacional',accuracyText:'Endereços, números de telefone, estado das entregas e registos de entrega exigem atenção.',learning:'Rapidez para aprender',learningText:'Usamos tecnologia e automação intensamente. A capacidade de aprender novos processos e ferramentas é importante.'},
    future:{heading:'Futuras oportunidades',text:'Nenhuma vaga atual se adequa? Pode enviar os seus dados para futuros recrutamentos em operações, experiência do cliente, vendas, tecnologia, finanças ou administração.',join:'Entrar no banco de talentos'},
    form:{heading:'Candidatar-se',role:'Vaga',roleLoading:'A carregar vagas…',roleSelect:'Selecione uma vaga…',name:'Nome completo',phone:'Telefone',phonePlaceholder:'07xx xxx xxx',email:'E-mail',location:'Localização',locationPlaceholder:'ex. Nairobi',summary:'Experiência relevante / por que se adequa',summaryPlaceholder:'Descreva brevemente a sua experiência, competências, disponibilidade e o que traria para a Lueri.',cv:'Link do CV / portfólio',linkedin:'LinkedIn (opcional)',availability:'Disponibilidade (opcional)',availabilityPlaceholder:'ex. Imediatamente / 30 dias',salary:'Salário esperado (opcional)',salaryPlaceholder:'Opcional',submit:'Enviar candidatura',privacy:'Solicitamos apenas informações necessárias para o recrutamento. Não envie palavras-passe, PIN KRA, números de identificação nacional, dados bancários ou outros documentos sensíveis nesta fase.'},
    messages:{roleRequired:'Selecione a vaga a que se está a candidatar.',name:'Introduza o seu nome completo.',phone:'Introduza um número de telefone queniano válido.',email:'Introduza um endereço de e-mail válido.',summary:'Forneça pelo menos um breve resumo da sua experiência relevante.',cv:'O link do CV / portfólio deve começar por https:// ou http://.',linkedin:'O link do LinkedIn deve começar por https:// ou http://.',roleUnavailable:'Esta vaga já não aceita candidaturas. Atualize a página e escolha outra vaga.',invalidName:'Introduza um nome completo válido.',invalidEmail:'Introduza um endereço de e-mail válido.',invalidPhone:'Introduza um número de telefone válido.',invalidSummary:'Forneça mais algumas informações sobre a sua experiência e adequação.',invalidCv:'Verifique o link do CV / portfólio.',invalidLinkedin:'Verifique o link do LinkedIn.',duplicate:'Já recebemos uma candidatura deste e-mail para esta vaga nas últimas 24 horas.',rate:'Foram feitas demasiadas tentativas a partir desta ligação. Tente novamente mais tarde.',submitFailed:'Não foi possível enviar a candidatura. Tente novamente.',received:'Candidatura recebida. A Lueri registou a sua candidatura para {role}. Mantenha o telefone e o e-mail disponíveis caso a equipa de recrutamento entre em contacto.',system:'O serviço de recrutamento está indisponível.',unavailableTitle:'As vagas estão temporariamente indisponíveis',submitted:'A enviar…'}
  };
  T.zh={
    meta:{title:'招聘 — Lueri International',description:'Lueri International 内罗毕当前招聘职位：运营、客户体验、销售及未来机会。'},
    nav:{where:'下一步去哪里',services:'服务',servicesCaption:'我们运输什么，以及速度如何',pricing:'价格',pricingCaption:'报价透明，无隐藏费用',business:'企业',businessCaption:'创建企业账户',coverage:'服务范围',coverageCaption:'我们在内罗毕的配送范围',why:'为什么选择我们',whyCaption:'Lueri 的不同之处',faq:'常见问题',faqCaption:'常见问题与答案',rewards:'奖励',rewardsCaption:'每次配送都可赚取积分',careers:'招聘',careersCaption:'Lueri 的职位机会',book:'预约',bookCaption:'立即提交取件请求',menu:'菜单',close:'关闭',bookPickup:'预约取件',theme:'切换深色模式',languageSelect:'选择语言'},
    hero:{eyebrow:'人才 / 招聘',form:'HR–2026 表格',title:'共建<br>网络。<br>与我们一起前进。',subtitle:'这里是 Lueri International 的招聘中心。查看真实开放职位、了解职位要求并直接申请。企业账户请前往企业页面。',open:'查看开放职位',future:'未来机会'},
    roles:{heading:'开放职位',loading:'正在加载当前职位…',emptyTitle:'目前没有开放职位',emptyText:'Lueri 目前没有确认公开招聘的职位。招聘开启后，新职位会显示在这里。',unavailable:'职位暂时无法使用<br>请稍后再试。申请系统仍受保护，尚未提交任何申请。',whatDo:'工作内容',fallback:'请查看下面的职位详情。',lookFor:'我们寻找的人才',apply:'查看职位并申请',futureOption:'未来机会 / 人才库'},
    values:{heading:'我们寻找的人才',ownership:'责任心',ownershipText:'把工作推进到完成，遇到阻碍及时沟通，并对结果负责。',customer:'客户意识',customerText:'客户着急或配送偏离计划时，保持清晰、冷静并提供有效帮助。',accuracy:'运营准确性',accuracyText:'地址、电话号码、配送状态和交接记录都需要仔细处理。',learning:'学习速度',learningText:'我们积极使用技术和自动化。快速学习新的流程和工具很重要。'},
    future:{heading:'未来机会',text:'目前没有合适职位？你仍可提交资料，供未来运营、客户体验、销售、技术、财务或行政岗位招聘参考。',join:'加入人才库'},
    form:{heading:'申请',role:'职位',roleLoading:'正在加载职位…',roleSelect:'请选择职位…',name:'姓名',phone:'电话',phonePlaceholder:'07xx xxx xxx',email:'电子邮箱',location:'所在地',locationPlaceholder:'例如 Nairobi',summary:'相关经验 / 为什么适合',summaryPlaceholder:'简要介绍你的相关经验、技能、可到岗时间以及你能为 Lueri 带来的价值。',cv:'简历 / 作品集链接',linkedin:'LinkedIn（可选）',availability:'可到岗时间（可选）',availabilityPlaceholder:'例如 立即 / 30 天',salary:'期望薪资（可选）',salaryPlaceholder:'可选',submit:'提交申请',privacy:'我们只收集招聘所需信息。现阶段请勿提交密码、KRA PIN、身份证号码、银行资料或其他敏感身份证明文件。'},
    messages:{roleRequired:'请选择你申请的职位。',name:'请输入姓名。',phone:'请输入有效的肯尼亚电话号码。',email:'请输入有效的电子邮箱。',summary:'请至少提供一段简短的相关经验介绍。',cv:'简历 / 作品集链接必须以 https:// 或 http:// 开头。',linkedin:'LinkedIn 链接必须以 https:// 或 http:// 开头。',roleUnavailable:'该职位已停止接受申请。请刷新页面并选择其他职位。',invalidName:'请输入有效姓名。',invalidEmail:'请输入有效邮箱。',invalidPhone:'请输入有效电话号码。',invalidSummary:'请提供更多关于经验和匹配度的信息。',invalidCv:'请检查简历 / 作品集链接。',invalidLinkedin:'请检查 LinkedIn 链接。',duplicate:'过去 24 小时内，我们已经收到该邮箱针对该职位的申请。',rate:'来自此连接的申请尝试过多。请稍后再试。',submitFailed:'无法提交申请，请重试。',received:'已收到申请。Lueri 已记录你对 {role} 的申请。如招聘团队联系，请保持电话和邮箱可用。',system:'招聘服务暂时不可用。',unavailableTitle:'职位暂时无法使用',submitted:'正在提交…'}
  };
  T.ar={
    meta:{title:'الوظائف — Lueri International',description:'الوظائف والفرص المهنية الحالية لدى Lueri International في نيروبي: العمليات وتجربة العملاء والمبيعات والفرص المستقبلية.'},
    nav:{where:'إلى أين بعد ذلك',services:'الخدمات',servicesCaption:'ما ننقله ومدى سرعتنا',pricing:'الأسعار',pricingCaption:'أسعار معلنة بلا رسوم خفية',business:'الأعمال',businessCaption:'إنشاء حساب شركة',coverage:'نطاق الخدمة',coverageCaption:'أين نوصّل في نيروبي',why:'لماذا نحن',whyCaption:'ما الذي يميز Lueri',faq:'الأسئلة الشائعة',faqCaption:'أسئلة شائعة وإجاباتها',rewards:'المكافآت',rewardsCaption:'اكسب نقاطًا مع كل توصيل',careers:'الوظائف',careersCaption:'فرص العمل في Lueri',book:'احجز',bookCaption:'أرسل طلب استلام الآن',menu:'القائمة',close:'إغلاق',bookPickup:'احجز الاستلام',theme:'تبديل الوضع الداكن',languageSelect:'اختيار اللغة'},
    hero:{eyebrow:'الأشخاص / الوظائف',form:'نموذج HR–2026',title:'ابنوا<br>الشبكة.<br>تحركوا معنا.',subtitle:'هذه هي منصة التوظيف في Lueri International. اطلع على الوظائف المفتوحة فعليًا، واقرأ المتطلبات وقدّم مباشرة. حسابات الشركات موجودة في صفحة الأعمال.',open:'عرض الوظائف المفتوحة',future:'الفرص المستقبلية'},
    roles:{heading:'الوظائف المفتوحة',loading:'جارٍ تحميل الوظائف الحالية…',emptyTitle:'لا توجد وظائف مفتوحة حاليًا',emptyText:'لا توجد لدى Lueri وظيفة عامة مؤكدة في الوقت الحالي. ستظهر الوظائف الجديدة هنا عند فتح التوظيف.',unavailable:'الوظائف غير متاحة مؤقتًا<br>يرجى المحاولة مرة أخرى بعد قليل. نظام التقديم محمي ولم يتم إرسال أي طلب.',whatDo:'المهام',fallback:'اطلع على تفاصيل الوظيفة أدناه.',lookFor:'ما نبحث عنه',apply:'عرض الوظيفة والتقديم',futureOption:'فرصة مستقبلية / قاعدة المواهب'},
    values:{heading:'ما نبحث عنه',ownership:'تحمل المسؤولية',ownershipText:'تابع العمل حتى النهاية، وأبلغ مبكرًا عند وجود عائق، وتحمل مسؤولية النتيجة.',customer:'الانضباط مع العملاء',customerText:'كن واضحًا وهادئًا ومفيدًا عندما يكون العميل مستعجلًا أو تخرج عملية التوصيل عن الخطة.',accuracy:'الدقة التشغيلية',accuracyText:'العناوين وأرقام الهاتف وحالة التوصيل وسجلات التسليم تحتاج إلى عناية.',learning:'سرعة التعلم',learningText:'نستخدم التقنية والأتمتة بكثافة. القدرة على تعلم عمليات وأدوات جديدة مهمة.'},
    future:{heading:'الفرص المستقبلية',text:'لا توجد وظيفة حالية تناسبك؟ يمكنك إرسال بياناتك لفرص التوظيف المستقبلية في العمليات وتجربة العملاء والمبيعات والتقنية والمالية والإدارة.',join:'انضم إلى قاعدة المواهب'},
    form:{heading:'التقديم',role:'الوظيفة',roleLoading:'جارٍ تحميل الوظائف…',roleSelect:'اختر وظيفة…',name:'الاسم الكامل',phone:'الهاتف',phonePlaceholder:'07xx xxx xxx',email:'البريد الإلكتروني',location:'الموقع',locationPlaceholder:'مثال: نيروبي',summary:'الخبرة ذات الصلة / لماذا أنت مناسب',summaryPlaceholder:'اذكر بإيجاز خبرتك ومهاراتك وتوافرك وما يمكنك إضافته إلى Lueri.',cv:'رابط السيرة الذاتية / الملف',linkedin:'LinkedIn (اختياري)',availability:'التوفر (اختياري)',availabilityPlaceholder:'مثال: فورًا / 30 يومًا',salary:'الراتب المتوقع (اختياري)',salaryPlaceholder:'اختياري',submit:'إرسال الطلب',privacy:'نطلب فقط المعلومات اللازمة للتوظيف. لا ترسل كلمات المرور أو PIN الخاص بـ KRA أو أرقام الهوية الوطنية أو بيانات البنك أو مستندات الهوية الحساسة في هذه المرحلة.'},
    messages:{roleRequired:'يرجى اختيار الوظيفة التي تتقدم إليها.',name:'يرجى إدخال اسمك الكامل.',phone:'يرجى إدخال رقم هاتف كيني صالح.',email:'يرجى إدخال بريد إلكتروني صالح.',summary:'يرجى تقديم ملخص قصير على الأقل عن خبرتك ذات الصلة.',cv:'يجب أن يبدأ رابط السيرة الذاتية بـ https:// أو http://.',linkedin:'يجب أن يبدأ رابط LinkedIn بـ https:// أو http://.',roleUnavailable:'لم تعد هذه الوظيفة تستقبل الطلبات. حدّث الصفحة واختر وظيفة أخرى.',invalidName:'يرجى إدخال اسم كامل صالح.',invalidEmail:'يرجى إدخال بريد إلكتروني صالح.',invalidPhone:'يرجى إدخال رقم هاتف صالح.',invalidSummary:'يرجى تقديم مزيد من المعلومات عن خبرتك ومدى ملاءمتك.',invalidCv:'يرجى التحقق من رابط السيرة الذاتية.',invalidLinkedin:'يرجى التحقق من رابط LinkedIn.',duplicate:'لقد تلقينا بالفعل طلبًا من هذا البريد لهذه الوظيفة خلال آخر 24 ساعة.',rate:'تم إجراء عدد كبير جدًا من المحاولات من هذا الاتصال. يرجى المحاولة لاحقًا.',submitFailed:'تعذر إرسال الطلب. يرجى المحاولة مرة أخرى.',received:'تم استلام الطلب. سجّلت Lueri طلبك لوظيفة {role}. أبقِ هاتفك وبريدك متاحين في حال تواصل فريق التوظيف.',system:'خدمة التوظيف غير متاحة.',unavailableTitle:'الوظائف غير متاحة مؤقتًا',submitted:'جارٍ الإرسال…'}
  };
  T.fr.rolesData={
    dispatch:{title:'Coordinateur(trice) Dispatch & Opérations',department:'Opérations',location:'Nairobi, Kenya',type:'Temps plein',summary:'Coordonner les collectes, les dispatchs, les incidents de livraison et les processus de preuve de livraison.',responsibilities:['Planification des dispatchs','Communication client','Gestion des incidents','Suivi des livraisons','Rapports quotidiens'],requirements:['Excellente organisation et suivi','Communication écrite et orale claire','À l’aise avec les outils CRM et de messagerie','Capacité à travailler dans un environnement de livraison dynamique']},
    support:{title:'Représentant(e) Service Client',department:'Expérience client',location:'Nairobi, Kenya',type:'Temps plein / Contrat',summary:'Gérer les échanges clients sur WhatsApp, téléphone, e-mail et les canaux numériques.',responsibilities:['Service client','Résolution des problèmes','Aide à la réservation','Mise à jour du CRM','Suivi du service'],requirements:['Excellente communication client','Résolution calme des problèmes','Tenue précise des dossiers','À l’aise avec les outils numériques de support']},
    sales:{title:'Représentant(e) Développement Commercial',department:'Ventes & Développement commercial',location:'Nairobi, Kenya',type:'Temps plein / Commission',summary:'Développer le portefeuille B2B de Lueri en créant des relations avec les entreprises ayant des besoins récurrents de livraison.',responsibilities:['Prospection','Prise de contact','Qualification des prospects','Génération de rendez-vous','Suivi du pipeline'],requirements:['Compétences en communication commerciale','Persévérance et suivi discipliné','Intérêt pour les ventes B2B','Capacité à comprendre les besoins clients']},
    future:{title:'Opportunité générale / future',department:'Vivier de talents',location:'Nairobi, Kenya',type:'Opportunité future',summary:'Envoyez votre CV pour de futures opportunités de recrutement chez Lueri International.',responsibilities:['Mise en relation avec de futures opportunités','Examen du vivier de talents'],requirements:['Communication claire','Expérience pertinente','Volonté d’apprendre']}
  };
  T.sw.rolesData={
    dispatch:{title:'Mratibu wa Dispatch na Uendeshaji',department:'Operations',location:'Nairobi, Kenya',type:'Muda wote',summary:'Ratibu pickups, dispatch, changamoto za delivery na taratibu za uthibitisho wa delivery.',responsibilities:['Mipango ya dispatch','Mawasiliano na wateja','Kushughulikia changamoto','Kufuatilia delivery','Ripoti za kila siku'],requirements:['Mpangilio na ufuatiliaji mzuri','Mawasiliano mazuri ya kuandika na kuzungumza','Uwezo wa kutumia CRM na zana za ujumbe','Uwezo wa kufanya kazi katika mazingira yenye kasi']},
    support:{title:'Mwakilishi wa Huduma kwa Wateja',department:'Uzoefu wa Mteja',location:'Nairobi, Kenya',type:'Muda wote / Mkataba',summary:'Simamia mawasiliano ya wateja kupitia WhatsApp, simu, barua pepe na njia za kidijitali.',responsibilities:['Huduma kwa wateja','Kutatuwa changamoto','Msaada wa booking','Masasisho ya CRM','Ufuatiliaji wa huduma'],requirements:['Mawasiliano bora ya huduma kwa wateja','Kutatuwa matatizo kwa utulivu','Utunzaji sahihi wa rekodi','Uwezo wa kutumia zana za kidijitali']},
    sales:{title:'Mwakilishi wa Maendeleo ya Biashara',department:'Mauzo na Maendeleo ya Biashara',location:'Nairobi, Kenya',type:'Muda wote / Tume',summary:'Jenga pipeline ya B2B ya Lueri kwa kuendeleza mahusiano na biashara zinazohitaji delivery za mara kwa mara.',responsibilities:['Kutafuta prospects','Mawasiliano ya mauzo','Kuchuja leads','Kuandaa mikutano','Ufuatiliaji wa pipeline'],requirements:['Ujuzi wa mawasiliano ya kibiashara','Uvumilivu na ufuatiliaji wa nidhamu','Nia ya mauzo ya B2B','Uwezo wa kuelewa mahitaji ya mteja']},
    future:{title:'Fursa ya Jumla / Baadaye',department:'Talent Pool',location:'Nairobi, Kenya',type:'Fursa ya baadaye',summary:'Tuma CV yako kwa fursa za ajira za baadaye katika Lueri International.',responsibilities:['Kulinganisha na fursa zijazo','Mapitio ya talent pool'],requirements:['Mawasiliano wazi','Uzoefu husika','Utayari wa kujifunza']}
  };
  T.pt.rolesData={
    dispatch:{title:'Coordenador(a) de Dispatch e Operações',department:'Operações',location:'Nairobi, Quénia',type:'Tempo inteiro',summary:'Coordenar recolhas, dispatch, exceções de entrega e processos de prova de entrega.',responsibilities:['Planeamento de dispatch','Comunicação com clientes','Gestão de exceções','Acompanhamento de entregas','Relatórios diários'],requirements:['Boa organização e acompanhamento','Comunicação escrita e oral clara','Conforto com CRM e ferramentas de mensagens','Capacidade de trabalhar num ambiente de entregas dinâmico']},
    support:{title:'Representante de Atendimento ao Cliente',department:'Experiência do Cliente',location:'Nairobi, Quénia',type:'Tempo inteiro / Contrato',summary:'Gerir conversas com clientes por WhatsApp, telefone, e-mail e canais digitais.',responsibilities:['Atendimento ao cliente','Resolução de problemas','Apoio a reservas','Atualização do CRM','Acompanhamento do serviço'],requirements:['Boa comunicação com clientes','Resolução calma de problemas','Registos precisos','Conforto com ferramentas digitais de suporte']},
    sales:{title:'Representante de Desenvolvimento de Negócio',department:'Vendas e Desenvolvimento de Negócio',location:'Nairobi, Quénia',type:'Tempo inteiro / Comissão',summary:'Construir o pipeline B2B da Lueri através de relações com empresas que precisam de entregas recorrentes.',responsibilities:['Prospecção','Contacto comercial','Qualificação de leads','Marcação de reuniões','Acompanhamento do pipeline'],requirements:['Comunicação comercial','Persistência e acompanhamento disciplinado','Interesse em vendas B2B','Capacidade de compreender necessidades do cliente']},
    future:{title:'Oportunidade Geral / Futura',department:'Banco de Talentos',location:'Nairobi, Quénia',type:'Oportunidade futura',summary:'Envie o seu CV para futuras oportunidades de recrutamento na Lueri International.',responsibilities:['Correspondência com futuras oportunidades','Revisão do banco de talentos'],requirements:['Comunicação clara','Experiência relevante','Vontade de aprender']}
  };
  T.zh.rolesData={
    dispatch:{title:'调度与运营协调员',department:'运营',location:'内罗毕，肯尼亚',type:'全职',summary:'协调取件、调度、配送异常和配送证明流程。',responsibilities:['调度规划','客户沟通','异常处理','配送跟踪','每日报告'],requirements:['组织能力强并善于跟进','良好的书面和口头沟通能力','熟悉 CRM 和消息工具','能够适应快速变化的配送环境']},
    support:{title:'客户支持代表',department:'客户体验',location:'内罗毕，肯尼亚',type:'全职 / 合同',summary:'通过 WhatsApp、电话、电子邮件和数字渠道负责客户沟通。',responsibilities:['客户支持','问题解决','预约协助','CRM 更新','服务跟进'],requirements:['优秀的客户服务沟通能力','冷静解决问题','准确记录信息','熟悉数字支持工具']},
    sales:{title:'业务拓展代表',department:'销售与业务拓展',location:'内罗毕，肯尼亚',type:'全职 / 佣金',summary:'通过发展与有持续配送需求的企业的关系，建立 Lueri 的 B2B 客户渠道。',responsibilities:['客户开发','商务联系','潜客筛选','会议邀约','销售管道跟进'],requirements:['商务沟通能力','坚持与有纪律的跟进能力','对 B2B 销售感兴趣','理解客户需求的能力']},
    future:{title:'通用 / 未来机会',department:'人才库',location:'内罗毕，肯尼亚',type:'未来机会',summary:'提交简历，供 Lueri International 未来招聘参考。',responsibilities:['未来职位匹配','人才库审核'],requirements:['沟通清晰','相关经验','愿意学习']}
  };
  T.ar.rolesData={
    dispatch:{title:'منسق التوزيع والعمليات',department:'العمليات',location:'نيروبي، كينيا',type:'دوام كامل',summary:'تنسيق عمليات الاستلام والتوزيع واستثناءات التسليم وإثبات التسليم.',responsibilities:['تخطيط التوزيع','التواصل مع العملاء','معالجة الحالات الاستثنائية','تتبع التوصيلات','التقارير اليومية'],requirements:['تنظيم ومتابعة قوية','تواصل واضح كتابيًا وشفهيًا','القدرة على استخدام CRM وأدوات المراسلة','القدرة على العمل في بيئة توصيل سريعة']},
    support:{title:'ممثل خدمة العملاء',department:'تجربة العملاء',location:'نيروبي، كينيا',type:'دوام كامل / عقد',summary:'إدارة محادثات العملاء عبر واتساب والهاتف والبريد الإلكتروني والقنوات الرقمية.',responsibilities:['خدمة العملاء','حل المشكلات','المساعدة في الحجز','تحديث CRM','متابعة الخدمة'],requirements:['تواصل قوي مع العملاء','حل المشكلات بهدوء','دقة في حفظ السجلات','القدرة على استخدام أدوات الدعم الرقمية']},
    sales:{title:'ممثل تطوير الأعمال',department:'المبيعات وتطوير الأعمال',location:'نيروبي، كينيا',type:'دوام كامل / عمولة',summary:'بناء قناة Lueri للأعمال B2B من خلال تطوير علاقات مع الشركات التي تحتاج إلى توصيل متكرر.',responsibilities:['استقطاب العملاء المحتملين','التواصل التجاري','تأهيل العملاء المحتملين','توليد الاجتماعات','متابعة خط المبيعات'],requirements:['مهارات التواصل التجاري','المثابرة والمتابعة المنضبطة','اهتمام بمبيعات B2B','القدرة على فهم احتياجات العملاء']},
    future:{title:'فرصة عامة / مستقبلية',department:'قاعدة المواهب',location:'نيروبي، كينيا',type:'فرصة مستقبلية',summary:'أرسل سيرتك الذاتية لفرص التوظيف المستقبلية في Lueri International.',responsibilities:['مطابقة الفرص المستقبلية','مراجعة قاعدة المواهب'],requirements:['تواصل واضح','خبرة ذات صلة','الاستعداد للتعلم']}
  };
  T.en.footer={registered:'Registered business',founded:'Founded 13 December 2023',registration:'Registration details available on request for B2B clients',contact:'Contact',hours:'Hours',weekdays:'Mon–Fri, 8:00 AM – 5:00 PM',saturday:'Sat, 8:00 AM – 3:00 PM',sunday:'Closed Sunday',skip:'Skip to application form',terms:'Terms',privacy:'Privacy'};
  T.es.footer={registered:'Empresa registrada',founded:'Fundada el 13 de diciembre de 2023',registration:'Información de registro disponible a solicitud para clientes B2B',contact:'Contacto',hours:'Horario',weekdays:'Lun–vie, 08:00–17:00',saturday:'Sáb., 08:00–15:00',sunday:'Cerrado el domingo',skip:'Ir al formulario de solicitud',terms:'Términos',privacy:'Privacidad'};
  T.fr.footer={registered:'Entreprise enregistrée',founded:'Fondée le 13 décembre 2023',registration:'Informations d’enregistrement disponibles sur demande pour les clients B2B',contact:'Contact',hours:'Horaires',weekdays:'Lun–ven, 08:00–17:00',saturday:'Sam., 08:00–15:00',sunday:'Fermé le dimanche',skip:'Aller au formulaire de candidature',terms:'Conditions',privacy:'Confidentialité'};
  T.sw.footer={registered:'Biashara iliyosajiliwa',founded:'Ilianzishwa 13 Desemba 2023',registration:'Maelezo ya usajili yanapatikana kwa ombi la wateja wa B2B',contact:'Mawasiliano',hours:'Saa za huduma',weekdays:'Jumatatu–Ijumaa, 08:00–17:00',saturday:'Jumamosi, 08:00–15:00',sunday:'Tumefungwa Jumapili',skip:'Nenda kwenye fomu ya maombi',terms:'Masharti',privacy:'Faragha'};
  T.pt.footer={registered:'Empresa registada',founded:'Fundada em 13 de dezembro de 2023',registration:'Informações de registo disponíveis mediante pedido para clientes B2B',contact:'Contacto',hours:'Horário',weekdays:'Seg–sex, 08:00–17:00',saturday:'Sáb., 08:00–15:00',sunday:'Encerrado ao domingo',skip:'Ir para o formulário de candidatura',terms:'Termos',privacy:'Privacidade'};
  T.zh.footer={registered:'注册企业',founded:'成立于 2023 年 12 月 13 日',registration:'B2B 客户可按要求获取注册信息',contact:'联系方式',hours:'营业时间',weekdays:'周一至周五，08:00–17:00',saturday:'周六，08:00–15:00',sunday:'周日休息',skip:'跳转到申请表',terms:'条款',privacy:'隐私'};
  T.ar.footer={registered:'شركة مسجلة',founded:'تأسست في 13 ديسمبر 2023',registration:'تتوفر معلومات التسجيل عند الطلب لعملاء B2B',contact:'اتصل بنا',hours:'ساعات العمل',weekdays:'الاثنين–الجمعة، 08:00–17:00',saturday:'السبت، 08:00–15:00',sunday:'مغلق يوم الأحد',skip:'انتقل إلى نموذج التقديم',terms:'الشروط',privacy:'الخصوصية'};
  function merge(dst,src){Object.keys(src||{}).forEach(function(k){if(src[k]&&typeof src[k]==='object'&&!Array.isArray(src[k])){dst[k]=dst[k]||{};merge(dst[k],src[k]);}else dst[k]=src[k];});}
  window.LueriI18n=window.LueriI18n||{translations:{}};
  LOCALES.forEach(function(l){window.LueriI18n.translations[l]=window.LueriI18n.translations[l]||{};merge(window.LueriI18n.translations[l],T[l]||T.en);});
  function locale(){var l=(new URLSearchParams(location.search).get('lang')||document.documentElement.dataset.lueriLanguage||localStorage.getItem('lueri_language')||'en').toLowerCase().split('-')[0];return LOCALES.indexOf(l)>=0?l:'en';}
  function role(role){var key=ROLE_KEYS[role.title];var d=(T[locale()]&&T[locale()].rolesData&&T[locale()].rolesData[key])||(T.en.rolesData[key]);if(!d)return null;return {title:d.title,department:d.department,location:d.location,type:d.type,summary:d.summary,description:d.description,responsibilities:d.responsibilities||[],requirements:d.requirements||[]};}
  function t(path){var l=locale(),v=(T[l]||T.en);return path.split('.').reduce(function(o,k){return o&&o[k];},v)||path.split('.').reduce(function(o,k){return o&&o[k];},T.en)||'';}
  function localizeLinks(){var l=locale();document.querySelectorAll('a[href]').forEach(function(a){var href=a.getAttribute('href');if(!href||href.charAt(0)==='#'||href.indexOf('mailto:')===0||href.indexOf('tel:')===0||href.indexOf('http')===0)return;try{var u=new URL(href,location.href);if(u.pathname.endsWith('.html')){u.searchParams.set('lang',l);a.setAttribute('href',u.pathname+'?'+u.searchParams.toString()+(u.hash||''));}}catch(_){}});}
  function applyMeta(){var l=locale(),m=T[l].meta;document.title=m.title;var d=document.querySelector('meta[name="description"]');if(d)d.setAttribute('content',m.description);}
  function applyStatic(){var l=locale();document.querySelectorAll('[data-careers-i18n]').forEach(function(el){var key=el.getAttribute('data-careers-i18n'),v=t(key);if(/<[a-z][\s\S]*>/i.test(v))el.innerHTML=v;else el.textContent=v;});document.querySelectorAll('[data-careers-placeholder]').forEach(function(el){el.setAttribute('placeholder',t(el.getAttribute('data-careers-placeholder')));});document.querySelectorAll('[data-careers-aria]').forEach(function(el){el.setAttribute('aria-label',t(el.getAttribute('data-careers-aria')));});applyMeta();localizeLinks();document.documentElement.lang=l==='zh'?'zh-CN':l;document.documentElement.dir=l==='ar'?'rtl':'ltr';document.documentElement.dataset.lueriLanguage=l;document.body.classList.toggle('rtl',l==='ar');}
  window.LueriCareersI18n={locales:LOCALES,locale:locale,t:t,role:role,apply:applyStatic};
  window.addEventListener('lueri:languagechange',function(){applyStatic();});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',applyStatic,{once:true});else applyStatic();
})();