/* Lueri International — seven-language client-side i18n
   Languages: English, Chinese, Kiswahili, French, Spanish, Arabic, Portuguese.
   No Google Translate or third-party translation widget is used.
*/
(function () {
  'use strict';

  const LANGS = ['en', 'zh', 'sw', 'fr', 'es', 'ar', 'pt'];
  const STORAGE_KEY = 'lueri_language';

  const translations = {
    en: {
      nav: { book:'Book Pickup', services:'Services', pricing:'Pricing', business:'Business', coverage:'Coverage', why:'Why Us', faq:'FAQ', rewards:'Rewards', careers:'Careers', menu:'Menu', where:'Where to next', servicesCaption:'What we carry, and how fast', pricingCaption:'Quoted rates, no hidden fees', businessCaption:'Set up a corporate account', coverageCaption:'Where we deliver in Nairobi', whyCaption:'What makes Lueri different', faqCaption:'Common questions, answered', rewardsCaption:'Earn points on every delivery', careersCaption:'Future roles at Lueri', bookCaption:'Send a pickup request now' },
      hero: { dispatch:'Dispatch / Nairobi & environs', waybill:'WAYBILL NO. LI–2026', title:'We move it\nacross Nairobi\ntoday.', subtitle:'Lueri International handles last-mile delivery and courier dispatch for individuals and businesses — parcels, documents, and e-commerce orders, picked up and delivered the same day across Nairobi.', scope:'Nairobi last-mile · Not cross-border freight', stamp:'Same-day dispatch', pickup:'PICKUP', dropoff:'DROP-OFF', bookBtn:'Book a Pickup', whatsappBtn:'WhatsApp Us' },
      booking: { heading:'Book a Delivery', intro:'Tell us what needs moving and where it should go. We will confirm the dispatch details with you.', pickup:'Pickup Location', pickupPlaceholder:'Enter pickup location', dropoff:'Drop-off Location', dropoffPlaceholder:'Enter destination', name:'Your Name', namePlaceholder:'Enter your full name', phone:'Phone Number', phonePlaceholder:'e.g. 0712 345 678', email:'Email Address', emailPlaceholder:'you@example.com', item:'What are you sending?', itemPlaceholder:'Parcel, document, gift, etc.', notes:'Additional Notes', notesPlaceholder:'Special instructions, landmark, recipient details…', submit:'Request Pickup', submitting:'Sending request…', success:'Booking received', successCopy:'Opening WhatsApp to confirm your dispatch…', openWhatsapp:'Open WhatsApp', close:'Close' },
      common: { learnMore:'Learn more', getQuote:'Get a Quote', sameDay:'Same-day delivery', secure:'Secure & reliable', support:'Customer support' },
      services: { title:'Services', subtitle:'Practical delivery services built around speed, reliability, and clear communication.', parcelTitle:'Parcel & document delivery', parcelText:'Point-to-point delivery across Nairobi for individuals — parcels, documents, gifts, and personal errands.', ecommerceTitle:'E-commerce delivery', ecommerceText:'Last-mile fulfilment for online sellers, including pickup, dispatch, and customer delivery.', businessTitle:'Business & corporate runs', businessText:'Scheduled and on-demand deliveries for offices, retailers, teams, and recurring business needs.', urgentTitle:'Urgent dispatch', urgentText:'Time-sensitive deliveries when the usual turnaround is not enough.', proofTitle:'Proof of delivery', proofText:'Delivery confirmation helps you know when and where the item was received.' },
      coverage: { title:'Coverage', subtitle:'Nairobi and surrounding areas, with dispatch planned around the route and service requirements.', body:'We focus on Nairobi last-mile delivery and nearby environs. For locations outside our standard operating area, contact us before booking so we can confirm availability.' },
      pricing: { title:'Pricing', subtitle:'Clear quoted rates with no hidden fees.', body:'Your delivery price depends on route, distance, parcel requirements, urgency, and any special handling. Request a quote before dispatch and we will confirm the amount with you.', note:'No hidden fees · Confirmed before dispatch' },
      why: { title:'Why Lueri', subtitle:'A straightforward delivery service built for people and businesses that value reliability.', oneTitle:'Clear communication', oneText:'We keep you informed about pickup, dispatch, and delivery status.', twoTitle:'Same-day focus', twoText:'We are built around practical same-day Nairobi delivery.', threeTitle:'Proof of delivery', threeText:'Completion is supported by delivery confirmation.', fourTitle:'Business-ready', fourText:'Recurring delivery needs can be structured around a corporate account.' },
      pod: { title:'Proof of Delivery', subtitle:'Visibility from dispatch to handover.', body:'We provide delivery confirmation so you have a clear record that the item reached the intended recipient.' },
      rewards: { title:'Rewards', subtitle:'Earn points as you deliver more with Lueri.', body:'Eligible customers can earn points and unlock Lueri membership benefits over time.', cta:'Explore Rewards' },
      faq: { title:'Frequently Asked Questions', q1:'What areas do you deliver to?', a1:'We primarily serve Nairobi and surrounding areas. Contact us for a location check before dispatch.', q2:'Do you offer same-day delivery?', a2:'Yes. Same-day delivery is a core service for eligible Nairobi routes and bookings.', q3:'How much does delivery cost?', a3:'Rates vary by route, distance, urgency, and parcel requirements. We quote before dispatch.', q4:'Can businesses use Lueri for recurring deliveries?', a4:'Yes. Businesses can discuss recurring delivery requirements and corporate account options with us.', q5:'How do I book a pickup?', a5:'Use the booking form, WhatsApp, or the contact channels provided on the site.', q6:'Can I send fragile or important documents?', a6:'Tell us what you are sending when booking so the dispatch requirements can be confirmed.', q7:'How do I know my delivery was completed?', a7:'Delivery completion is supported by proof-of-delivery confirmation.', q8:'Can I contact someone directly?', a8:'Yes. Use WhatsApp or the contact details provided on the site.' },
      footer: { about:'Nairobi last-mile delivery and courier dispatch for individuals and businesses.', links:'Quick Links', contact:'Contact', hours:'Hours', hoursValue:'Mon–Fri 08:00–17:00 · Sat 08:00–15:00', rights:'All rights reserved.' },
      form: { required:'Required', optional:'Optional' }
    },
    zh: {
      nav: { book:'预约取件', services:'服务', pricing:'价格', business:'企业服务', coverage:'配送范围', why:'为何选择我们', faq:'常见问题', rewards:'奖励', careers:'招聘', menu:'菜单', where:'下一站', servicesCaption:'我们运输什么，以及多快', pricingCaption:'透明报价，无隐藏费用', businessCaption:'建立企业账户', coverageCaption:'内罗毕配送范围', whyCaption:'Lueri 的不同之处', faqCaption:'常见问题解答', rewardsCaption:'每次配送都可赚取积分', careersCaption:'Lueri 招聘机会', bookCaption:'立即提交取件请求' },
      hero: { dispatch:'配送 / 内罗毕及周边', waybill:'运单号 LI–2026', title:'今天，\n我们把它\n送遍内罗毕。', subtitle:'Lueri International 为个人和企业提供最后一公里配送与快递服务——包裹、文件和电商订单，可在内罗毕当天取件并送达。', scope:'内罗毕最后一公里 · 不提供跨境货运', stamp:'当天配送', pickup:'取件', dropoff:'送达', bookBtn:'预约取件', whatsappBtn:'WhatsApp 联系我们' },
      booking: { heading:'预约配送', intro:'告诉我们要运送什么以及目的地，我们会与您确认配送详情。', pickup:'取件地点', pickupPlaceholder:'输入取件地点', dropoff:'送达地点', dropoffPlaceholder:'输入目的地', name:'您的姓名', namePlaceholder:'输入姓名', phone:'电话号码', phonePlaceholder:'例如 0712 345 678', email:'电子邮箱', emailPlaceholder:'you@example.com', item:'您要发送什么？', itemPlaceholder:'包裹、文件、礼物等', notes:'补充说明', notesPlaceholder:'特殊要求、地标、收件人信息……', submit:'提交取件请求', submitting:'正在发送请求……', success:'已收到预约', successCopy:'正在打开 WhatsApp 以确认配送……', openWhatsapp:'打开 WhatsApp', close:'关闭' },
      common:{ learnMore:'了解更多', getQuote:'获取报价', sameDay:'当天配送', secure:'安全可靠', support:'客户支持' },
      services:{title:'服务',subtitle:'围绕速度、可靠性和清晰沟通打造的实用配送服务。',parcelTitle:'包裹与文件配送',parcelText:'覆盖内罗毕的点对点配送，适用于包裹、文件、礼物和个人事务。',ecommerceTitle:'电商配送',ecommerceText:'为网店提供最后一公里履约，包括取件、派送和客户交付。',businessTitle:'企业与商务配送',businessText:'为办公室、零售商、团队和长期业务需求提供计划或按需配送。',urgentTitle:'紧急配送',urgentText:'适合时间敏感型配送。',proofTitle:'配送证明',proofText:'提供配送确认，让您知道物品何时何地被接收。'},
      coverage:{title:'配送范围',subtitle:'内罗毕及周边地区，根据路线和服务要求安排配送。',body:'我们专注于内罗毕最后一公里配送及周边地区。如目的地超出常规服务范围，请在预约前联系我们确认。'},
      pricing:{title:'价格',subtitle:'透明报价，无隐藏费用。',body:'价格取决于路线、距离、包裹要求、时效和特殊处理。请在派送前索取报价，我们会确认最终金额。',note:'无隐藏费用 · 派送前确认'},
      why:{title:'为何选择 Lueri',subtitle:'为重视可靠性的个人和企业打造的直接、高效配送服务。',oneTitle:'清晰沟通',oneText:'我们及时告知您取件、派送和交付状态。',twoTitle:'专注当天配送',twoText:'我们围绕内罗毕实用的当天配送服务构建。',threeTitle:'配送证明',threeText:'以配送确认支持任务完成。',fourTitle:'企业友好',fourText:'可围绕企业账户安排长期配送需求。'},
      pod:{title:'配送证明',subtitle:'从派送到交接，全程可追踪。',body:'我们提供配送确认，让您清楚知道物品已送达指定收件人。'},
      rewards:{title:'奖励',subtitle:'使用 Lueri 越多，积分越多。',body:'符合条件的客户可赚取积分，并逐步解锁会员权益。',cta:'查看奖励'},
      faq:{title:'常见问题',q1:'你们配送到哪些地区？',a1:'我们主要服务内罗毕及周边地区。派送前可联系我们确认具体地点。',q2:'提供当天配送吗？',a2:'是的。当天配送是符合条件的内罗毕路线和预约的核心服务。',q3:'配送费用是多少？',a3:'费用取决于路线、距离、时效和包裹要求。派送前会先报价。',q4:'企业可以使用 Lueri 做长期配送吗？',a4:'可以。企业可与我们讨论长期配送需求及企业账户方案。',q5:'如何预约取件？',a5:'可使用网站表单、WhatsApp 或网站上的联系方式。',q6:'可以寄送易碎品或重要文件吗？',a6:'预约时请说明物品类型，我们会确认配送要求。',q7:'如何确认配送完成？',a7:'配送完成后会提供配送确认。',q8:'可以直接联系工作人员吗？',a8:'可以。请使用 WhatsApp 或网站上的联系方式。'},
      footer:{about:'为个人和企业提供内罗毕最后一公里配送与快递服务。',links:'快速链接',contact:'联系',hours:'营业时间',hoursValue:'周一至周五 08:00–17:00 · 周六 08:00–15:00',rights:'版权所有。'}
    },
    sw: {
      nav:{book:'Agiza Kuchukuliwa',services:'Huduma',pricing:'Bei',business:'Biashara',coverage:'Maeneo Tunayofikisha',why:'Kwa Nini Sisi',faq:'Maswali',rewards:'Zawadi',careers:'Ajira',menu:'Menyu',where:'Uende Wapi',servicesCaption:'Tunabeba nini na kwa kasi gani',pricingCaption:'Bei iliyonukuliwa, hakuna gharama fiche',businessCaption:'Fungua akaunti ya kampuni',coverageCaption:'Maeneo tunayofikisha Nairobi',whyCaption:'Kinachotutofautisha',faqCaption:'Maswali ya kawaida yamejibiwa',rewardsCaption:'Pata pointi kwa kila uwasilishaji',careersCaption:'Nafasi za baadaye Lueri',bookCaption:'Tuma ombi la kuchukuliwa sasa'},
      hero:{dispatch:'Usafirishaji / Nairobi na viunga',waybill:'NAMBA YA WAYBILL LI–2026',title:'Tunaisafirisha\nNairobi nzima\nleo.',subtitle:'Lueri International hutoa huduma za last-mile delivery na courier kwa watu binafsi na biashara — vifurushi, nyaraka na oda za biashara mtandaoni, vikichukuliwa na kufikishwa siku hiyo hiyo Nairobi.',scope:'Last-mile Nairobi · Sio usafirishaji wa mipakani',stamp:'Usafirishaji wa siku hiyo',pickup:'KUCHUKUA',dropoff:'KUFIKISHA',bookBtn:'Agiza Kuchukuliwa',whatsappBtn:'Tupigie WhatsApp'},
      booking:{heading:'Agiza Uwasilishaji',intro:'Tuambie kinachohitaji kusafirishwa na kinakoenda. Tutathibitisha maelezo ya uwasilishaji nawe.',pickup:'Mahali pa Kuchukua',pickupPlaceholder:'Weka mahali pa kuchukua',dropoff:'Mahali pa Kufikisha',dropoffPlaceholder:'Weka unakoenda',name:'Jina Lako',namePlaceholder:'Weka jina lako kamili',phone:'Nambari ya Simu',phonePlaceholder:'mf. 0712 345 678',email:'Barua Pepe',emailPlaceholder:'you@example.com',item:'Unatuma Nini?',itemPlaceholder:'Kifurushi, nyaraka, zawadi, n.k.',notes:'Maelezo ya Ziada',notesPlaceholder:'Maelekezo maalum, alama ya eneo, maelezo ya mpokeaji…',submit:'Omba Kuchukuliwa',submitting:'Inatuma ombi…',success:'Ombi limepokelewa',successCopy:'Tunafungua WhatsApp kuthibitisha uwasilishaji…',openWhatsapp:'Fungua WhatsApp',close:'Funga'},
      common:{learnMore:'Jifunze zaidi',getQuote:'Pata Bei',sameDay:'Uwasilishaji siku hiyo hiyo',secure:'Salama na ya kuaminika',support:'Huduma kwa wateja'},
      services:{title:'Huduma',subtitle:'Huduma za usafirishaji zinazolenga kasi, uaminifu na mawasiliano wazi.',parcelTitle:'Uwasilishaji wa vifurushi na nyaraka',parcelText:'Uwasilishaji wa hatua kwa hatua Nairobi kwa watu binafsi — vifurushi, nyaraka, zawadi na shughuli binafsi.',ecommerceTitle:'Uwasilishaji wa biashara mtandaoni',ecommerceText:'Huduma ya mwisho ya uwasilishaji kwa wauzaji mtandaoni, ikijumuisha kuchukua, kusafirisha na kumfikishia mteja.',businessTitle:'Uwasilishaji wa biashara na kampuni',businessText:'Uwasilishaji uliopangwa au wa mahitaji kwa ofisi, wauzaji, timu na biashara zinazohitaji mara kwa mara.',urgentTitle:'Usafirishaji wa haraka',urgentText:'Kwa uwasilishaji unaohitaji kufanyika haraka.',proofTitle:'Uthibitisho wa uwasilishaji',proofText:'Tunatoa uthibitisho ili ujue kifurushi kimepokelewa lini na wapi.'},
      coverage:{title:'Maeneo Tunayofikisha',subtitle:'Nairobi na viunga, kulingana na njia na mahitaji ya huduma.',body:'Tunazingatia last-mile delivery Nairobi na maeneo ya karibu. Kwa maeneo yaliyo nje ya kawaida, wasiliana nasi kabla ya kuagiza ili kuthibitisha upatikanaji.'},
      pricing:{title:'Bei',subtitle:'Bei iliyonukuliwa wazi bila gharama fiche.',body:'Bei hutegemea njia, umbali, mahitaji ya kifurushi, uharaka na huduma maalum. Omba bei kabla ya usafirishaji na tutathibitisha kiasi.',note:'Hakuna gharama fiche · Thibitishwa kabla ya usafirishaji'},
      why:{title:'Kwa Nini Lueri',subtitle:'Huduma rahisi ya uwasilishaji kwa watu na biashara zinazothamini uaminifu.',oneTitle:'Mawasiliano wazi',oneText:'Tunakuarifu kuhusu kuchukua, kusafirisha na kufikisha.',twoTitle:'Mkazo wa siku hiyo',twoText:'Tumejengwa kwa uwasilishaji wa siku hiyo Nairobi.',threeTitle:'Uthibitisho wa uwasilishaji',threeText:'Kukamilika kunathibitishwa kwa uthibitisho wa kufikisha.',fourTitle:'Tayari kwa biashara',fourText:'Mahitaji ya mara kwa mara yanaweza kupangwa kupitia akaunti ya kampuni.'},
      pod:{title:'Uthibitisho wa Uwasilishaji',subtitle:'Mwonekano kutoka usafirishaji hadi makabidhiano.',body:'Tunatoa uthibitisho wa uwasilishaji ili uwe na rekodi wazi kuwa kifurushi kimemfikia mpokeaji aliyekusudiwa.'},
      rewards:{title:'Zawadi',subtitle:'Pata pointi unapofanya uwasilishaji zaidi na Lueri.',body:'Wateja wanaostahili wanaweza kupata pointi na kufungua faida za uanachama.',cta:'Angalia Zawadi'},
      faq:{title:'Maswali Yanayoulizwa Mara kwa Mara',q1:'Mnafikisha maeneo gani?',a1:'Tunatumikia zaidi Nairobi na viunga. Wasiliana nasi kuthibitisha eneo kabla ya usafirishaji.',q2:'Mna uwasilishaji wa siku hiyo hiyo?',a2:'Ndiyo. Uwasilishaji wa siku hiyo ni huduma kuu kwa njia na oda zinazostahili Nairobi.',q3:'Uwasilishaji unagharimu kiasi gani?',a3:'Bei hutegemea njia, umbali, uharaka na mahitaji ya kifurushi. Tunatoa bei kabla ya usafirishaji.',q4:'Biashara zinaweza kutumia Lueri mara kwa mara?',a4:'Ndiyo. Biashara zinaweza kujadili mahitaji ya kila mara na chaguo za akaunti ya kampuni.',q5:'Ninaagizaje kuchukuliwa?',a5:'Tumia fomu ya booking, WhatsApp au njia za mawasiliano kwenye tovuti.',q6:'Naweza kutuma vitu vya kuvunjika au nyaraka muhimu?',a6:'Tuambie unachotuma wakati wa booking ili kuthibitisha mahitaji ya usafirishaji.',q7:'Nitajuaje uwasilishaji umekamilika?',a7:'Uwasilishaji hukamilika kwa uthibitisho wa kufikisha.',q8:'Naweza kuwasiliana na mtu moja kwa moja?',a8:'Ndiyo. Tumia WhatsApp au mawasiliano yaliyo kwenye tovuti.'},
      footer:{about:'Uwasilishaji wa last-mile Nairobi na courier kwa watu binafsi na biashara.',links:'Viungo vya Haraka',contact:'Mawasiliano',hours:'Muda wa Kazi',hoursValue:'Jumatatu–Ijumaa 08:00–17:00 · Jumamosi 08:00–15:00',rights:'Haki zote zimehifadhiwa.'}
    },
    fr: {
      nav:{book:'Réserver un enlèvement',services:'Services',pricing:'Tarifs',business:'Entreprises',coverage:'Couverture',why:'Pourquoi nous',faq:'FAQ',rewards:'Récompenses',careers:'Carrières',menu:'Menu',where:'Où aller ensuite',servicesCaption:'Ce que nous transportons et à quelle vitesse',pricingCaption:'Tarifs sur devis, sans frais cachés',businessCaption:'Créer un compte professionnel',coverageCaption:'Où nous livrons à Nairobi',whyCaption:'Ce qui distingue Lueri',faqCaption:'Questions fréquentes, réponses',rewardsCaption:'Gagnez des points à chaque livraison',careersCaption:'Futurs postes chez Lueri',bookCaption:'Envoyer une demande d’enlèvement'},
      hero:{dispatch:'Expédition / Nairobi et environs',waybill:'N° DE BON LI–2026',title:'Nous livrons\nà travers Nairobi\naujourd’hui.',subtitle:'Lueri International assure la livraison du dernier kilomètre et les services de coursier pour particuliers et entreprises — colis, documents et commandes e-commerce, retirés et livrés le jour même à Nairobi.',scope:'Dernier kilomètre Nairobi · Pas de fret transfrontalier',stamp:'Livraison le jour même',pickup:'ENLÈVEMENT',dropoff:'LIVRAISON',bookBtn:'Réserver un enlèvement',whatsappBtn:'Nous écrire sur WhatsApp'},
      booking:{heading:'Réserver une livraison',intro:'Indiquez ce qui doit être transporté et sa destination. Nous confirmerons avec vous les détails de l’envoi.',pickup:'Lieu d’enlèvement',pickupPlaceholder:'Saisissez le lieu d’enlèvement',dropoff:'Lieu de livraison',dropoffPlaceholder:'Saisissez la destination',name:'Votre nom',namePlaceholder:'Saisissez votre nom complet',phone:'Numéro de téléphone',phonePlaceholder:'ex. 0712 345 678',email:'Adresse e-mail',emailPlaceholder:'you@example.com',item:'Que souhaitez-vous envoyer ?',itemPlaceholder:'Colis, document, cadeau, etc.',notes:'Notes supplémentaires',notesPlaceholder:'Instructions, repère, informations du destinataire…',submit:'Demander un enlèvement',submitting:'Envoi de la demande…',success:'Demande reçue',successCopy:'Ouverture de WhatsApp pour confirmer votre envoi…',openWhatsapp:'Ouvrir WhatsApp',close:'Fermer'},
      common:{learnMore:'En savoir plus',getQuote:'Obtenir un devis',sameDay:'Livraison le jour même',secure:'Sûr et fiable',support:'Service client'},
      services:{title:'Services',subtitle:'Des services de livraison pratiques, conçus pour la rapidité, la fiabilité et une communication claire.',parcelTitle:'Livraison de colis et documents',parcelText:'Livraison porte à porte à Nairobi pour les particuliers — colis, documents, cadeaux et courses personnelles.',ecommerceTitle:'Livraison e-commerce',ecommerceText:'Logistique du dernier kilomètre pour vendeurs en ligne : enlèvement, expédition et remise au client.',businessTitle:'Livraisons professionnelles et d’entreprise',businessText:'Livraisons planifiées ou à la demande pour bureaux, commerces, équipes et besoins récurrents.',urgentTitle:'Expédition urgente',urgentText:'Pour les livraisons sensibles au facteur temps.',proofTitle:'Preuve de livraison',proofText:'Une confirmation de livraison vous permet de savoir quand et où l’article a été reçu.'},
      coverage:{title:'Couverture',subtitle:'Nairobi et environs, selon l’itinéraire et les exigences du service.',body:'Nous nous concentrons sur la livraison du dernier kilomètre à Nairobi et dans les environs. Pour une zone hors couverture standard, contactez-nous avant de réserver.'},
      pricing:{title:'Tarifs',subtitle:'Devis clairs, sans frais cachés.',body:'Le prix dépend de l’itinéraire, de la distance, du colis, de l’urgence et des besoins particuliers. Demandez un devis avant l’envoi.',note:'Sans frais cachés · Confirmé avant expédition'},
      why:{title:'Pourquoi Lueri',subtitle:'Un service de livraison direct pour les particuliers et entreprises qui recherchent la fiabilité.',oneTitle:'Communication claire',oneText:'Nous vous tenons informé de l’enlèvement, de l’expédition et de la livraison.',twoTitle:'Priorité au jour même',twoText:'Notre service est conçu pour la livraison le jour même à Nairobi.',threeTitle:'Preuve de livraison',threeText:'Chaque livraison est accompagnée d’une confirmation.',fourTitle:'Prêt pour les entreprises',fourText:'Les besoins récurrents peuvent être structurés via un compte professionnel.'},
      pod:{title:'Preuve de livraison',subtitle:'Visibilité de l’expédition à la remise.',body:'Nous fournissons une confirmation afin que vous sachiez clairement que l’article est arrivé chez le destinataire.'},
      rewards:{title:'Récompenses',subtitle:'Gagnez des points à mesure que vous livrez avec Lueri.',body:'Les clients éligibles peuvent accumuler des points et débloquer des avantages de membre.',cta:'Voir les récompenses'},
      faq:{title:'Questions fréquentes',q1:'Dans quelles zones livrez-vous ?',a1:'Nous desservons principalement Nairobi et ses environs. Contactez-nous pour vérifier une zone précise.',q2:'Proposez-vous la livraison le jour même ?',a2:'Oui. La livraison le jour même est un service central pour les itinéraires et réservations éligibles à Nairobi.',q3:'Combien coûte une livraison ?',a3:'Le tarif dépend de l’itinéraire, de la distance, de l’urgence et du colis. Le devis est confirmé avant expédition.',q4:'Les entreprises peuvent-elles utiliser Lueri régulièrement ?',a4:'Oui. Nous pouvons discuter des besoins récurrents et des options de compte professionnel.',q5:'Comment réserver un enlèvement ?',a5:'Utilisez le formulaire, WhatsApp ou les coordonnées indiquées sur le site.',q6:'Puis-je envoyer des objets fragiles ou des documents importants ?',a6:'Indiquez ce que vous envoyez afin que les conditions de livraison soient confirmées.',q7:'Comment savoir si la livraison est terminée ?',a7:'Une preuve de livraison confirme la finalisation.',q8:'Puis-je parler directement à quelqu’un ?',a8:'Oui. Utilisez WhatsApp ou les coordonnées du site.'},
      footer:{about:'Livraison du dernier kilomètre et service de coursier à Nairobi pour particuliers et entreprises.',links:'Liens rapides',contact:'Contact',hours:'Horaires',hoursValue:'Lun–Ven 08:00–17:00 · Sam 08:00–15:00',rights:'Tous droits réservés.'}
    },
    es: {
      nav:{book:'Reservar recogida',services:'Servicios',pricing:'Precios',business:'Empresas',coverage:'Cobertura',why:'Por qué nosotros',faq:'Preguntas frecuentes',rewards:'Recompensas',careers:'Empleo',menu:'Menú',where:'A dónde ir',servicesCaption:'Qué transportamos y qué tan rápido',pricingCaption:'Tarifas cotizadas, sin cargos ocultos',businessCaption:'Configurar una cuenta corporativa',coverageCaption:'Dónde entregamos en Nairobi',whyCaption:'Qué diferencia a Lueri',faqCaption:'Preguntas comunes, respuestas',rewardsCaption:'Gana puntos con cada entrega',careersCaption:'Futuras oportunidades en Lueri',bookCaption:'Enviar una solicitud de recogida'},
      hero:{dispatch:'Despacho / Nairobi y alrededores',waybill:'N.º DE GUÍA LI–2026',title:'Lo movemos\npor Nairobi\nhoy.',subtitle:'Lueri International gestiona entregas de última milla y servicios de mensajería para particulares y empresas — paquetes, documentos y pedidos de comercio electrónico, recogidos y entregados el mismo día en Nairobi.',scope:'Última milla Nairobi · No transporte transfronterizo',stamp:'Despacho el mismo día',pickup:'RECOGIDA',dropoff:'ENTREGA',bookBtn:'Reservar recogida',whatsappBtn:'Escríbenos por WhatsApp'},
      booking:{heading:'Reservar una entrega',intro:'Indícanos qué necesitas enviar y a dónde debe llegar. Confirmaremos contigo los detalles del despacho.',pickup:'Lugar de recogida',pickupPlaceholder:'Introduce el lugar de recogida',dropoff:'Lugar de entrega',dropoffPlaceholder:'Introduce el destino',name:'Tu nombre',namePlaceholder:'Introduce tu nombre completo',phone:'Número de teléfono',phonePlaceholder:'ej. 0712 345 678',email:'Correo electrónico',emailPlaceholder:'you@example.com',item:'¿Qué estás enviando?',itemPlaceholder:'Paquete, documento, regalo, etc.',notes:'Notas adicionales',notesPlaceholder:'Instrucciones, referencia del lugar, datos del destinatario…',submit:'Solicitar recogida',submitting:'Enviando solicitud…',success:'Solicitud recibida',successCopy:'Abriendo WhatsApp para confirmar el despacho…',openWhatsapp:'Abrir WhatsApp',close:'Cerrar'},
      common:{learnMore:'Más información',getQuote:'Solicitar cotización',sameDay:'Entrega el mismo día',secure:'Seguro y fiable',support:'Atención al cliente'},
      services:{title:'Servicios',subtitle:'Servicios de entrega prácticos centrados en velocidad, fiabilidad y comunicación clara.',parcelTitle:'Entrega de paquetes y documentos',parcelText:'Entrega punto a punto en Nairobi para particulares: paquetes, documentos, regalos y recados personales.',ecommerceTitle:'Entregas de comercio electrónico',ecommerceText:'Última milla para vendedores online, incluyendo recogida, despacho y entrega al cliente.',businessTitle:'Entregas empresariales y corporativas',businessText:'Entregas programadas y bajo demanda para oficinas, comercios, equipos y necesidades recurrentes.',urgentTitle:'Despacho urgente',urgentText:'Para entregas en las que el tiempo es crítico.',proofTitle:'Prueba de entrega',proofText:'La confirmación de entrega te permite saber cuándo y dónde se recibió el artículo.'},
      coverage:{title:'Cobertura',subtitle:'Nairobi y alrededores, según la ruta y los requisitos del servicio.',body:'Nos especializamos en entregas de última milla en Nairobi y zonas cercanas. Para ubicaciones fuera del área estándar, contáctanos antes de reservar.'},
      pricing:{title:'Precios',subtitle:'Cotizaciones claras, sin cargos ocultos.',body:'El precio depende de la ruta, distancia, requisitos del paquete, urgencia y manejo especial. Solicita una cotización antes del despacho.',note:'Sin cargos ocultos · Confirmado antes del despacho'},
      why:{title:'Por qué Lueri',subtitle:'Un servicio de entrega directo para personas y empresas que valoran la fiabilidad.',oneTitle:'Comunicación clara',oneText:'Te mantenemos al tanto de la recogida, el despacho y la entrega.',twoTitle:'Enfoque en el mismo día',twoText:'Estamos diseñados para la entrega práctica el mismo día en Nairobi.',threeTitle:'Prueba de entrega',threeText:'La finalización se respalda con confirmación de entrega.',fourTitle:'Preparados para empresas',fourText:'Las necesidades recurrentes pueden organizarse mediante una cuenta corporativa.'},
      pod:{title:'Prueba de entrega',subtitle:'Visibilidad desde el despacho hasta la entrega.',body:'Proporcionamos confirmación para que tengas un registro claro de que el artículo llegó al destinatario previsto.'},
      rewards:{title:'Recompensas',subtitle:'Gana puntos mientras realizas más entregas con Lueri.',body:'Los clientes elegibles pueden ganar puntos y desbloquear beneficios de membresía.',cta:'Explorar recompensas'},
      faq:{title:'Preguntas frecuentes',q1:'¿A qué zonas entregan?',a1:'Servimos principalmente Nairobi y sus alrededores. Contáctanos para comprobar una ubicación concreta.',q2:'¿Ofrecen entrega el mismo día?',a2:'Sí. Es un servicio principal para rutas y reservas elegibles en Nairobi.',q3:'¿Cuánto cuesta una entrega?',a3:'La tarifa depende de la ruta, distancia, urgencia y requisitos del paquete. Cotizamos antes del despacho.',q4:'¿Las empresas pueden usar Lueri de forma recurrente?',a4:'Sí. Podemos hablar sobre necesidades periódicas y opciones de cuenta corporativa.',q5:'¿Cómo reservo una recogida?',a5:'Usa el formulario, WhatsApp o los datos de contacto del sitio.',q6:'¿Puedo enviar artículos frágiles o documentos importantes?',a6:'Indica qué envías para que podamos confirmar los requisitos del despacho.',q7:'¿Cómo sé que la entrega se completó?',a7:'La confirmación de entrega respalda la finalización.',q8:'¿Puedo hablar directamente con alguien?',a8:'Sí. Usa WhatsApp o los datos de contacto del sitio.'},
      footer:{about:'Entrega de última milla y mensajería en Nairobi para particulares y empresas.',links:'Enlaces rápidos',contact:'Contacto',hours:'Horario',hoursValue:'Lun–Vie 08:00–17:00 · Sáb 08:00–15:00',rights:'Todos los derechos reservados.'}
    },
    ar: {
      nav:{book:'احجز الاستلام',services:'الخدمات',pricing:'الأسعار',business:'الشركات',coverage:'نطاق التغطية',why:'لماذا لويري',faq:'الأسئلة الشائعة',rewards:'المكافآت',careers:'الوظائف',menu:'القائمة',where:'إلى أين بعد ذلك',servicesCaption:'ما الذي ننقله ومدى السرعة',pricingCaption:'أسعار واضحة بلا رسوم مخفية',businessCaption:'إنشاء حساب للشركات',coverageCaption:'مناطق التوصيل في نيروبي',whyCaption:'ما الذي يميز لويري',faqCaption:'إجابات عن الأسئلة الشائعة',rewardsCaption:'اكسب نقاطًا مع كل عملية توصيل',careersCaption:'الفرص المستقبلية في لويري',bookCaption:'أرسل طلب استلام الآن'},
      hero:{dispatch:'التوصيل / نيروبي والمناطق المحيطة',waybill:'رقم بوليصة LI–2026',title:'ننقلها\nعبر نيروبي\nاليوم.',subtitle:'تقدم Lueri International خدمات التوصيل للمرحلة الأخيرة والطرود للأفراد والشركات — الطرود والمستندات وطلبات التجارة الإلكترونية، مع الاستلام والتسليم في اليوم نفسه داخل نيروبي.',scope:'التوصيل داخل نيروبي · ليس شحنًا عابرًا للحدود',stamp:'توصيل في اليوم نفسه',pickup:'استلام',dropoff:'تسليم',bookBtn:'احجز الاستلام',whatsappBtn:'راسلنا عبر واتساب'},
      booking:{heading:'احجز عملية توصيل',intro:'أخبرنا بما تريد نقله وإلى أين. سنؤكد معك تفاصيل التوصيل.',pickup:'موقع الاستلام',pickupPlaceholder:'أدخل موقع الاستلام',dropoff:'موقع التسليم',dropoffPlaceholder:'أدخل الوجهة',name:'اسمك',namePlaceholder:'أدخل اسمك الكامل',phone:'رقم الهاتف',phonePlaceholder:'مثال 0712 345 678',email:'البريد الإلكتروني',emailPlaceholder:'you@example.com',item:'ماذا ترسل؟',itemPlaceholder:'طرد، مستند، هدية، إلخ.',notes:'ملاحظات إضافية',notesPlaceholder:'تعليمات خاصة، معلم قريب، بيانات المستلم…',submit:'طلب الاستلام',submitting:'جارٍ إرسال الطلب…',success:'تم استلام الطلب',successCopy:'نفتح واتساب لتأكيد عملية التوصيل…',openWhatsapp:'فتح واتساب',close:'إغلاق'},
      common:{learnMore:'اعرف المزيد',getQuote:'احصل على عرض سعر',sameDay:'توصيل في اليوم نفسه',secure:'آمن وموثوق',support:'دعم العملاء'},
      services:{title:'الخدمات',subtitle:'خدمات توصيل عملية تركز على السرعة والموثوقية والتواصل الواضح.',parcelTitle:'توصيل الطرود والمستندات',parcelText:'توصيل من نقطة إلى نقطة داخل نيروبي للأفراد — طرود ومستندات وهدايا ومهام شخصية.',ecommerceTitle:'توصيل التجارة الإلكترونية',ecommerceText:'تنفيذ للمرحلة الأخيرة للبائعين عبر الإنترنت، بما في ذلك الاستلام والشحن والتسليم للعميل.',businessTitle:'خدمات الشركات والأعمال',businessText:'توصيلات مجدولة وعند الطلب للمكاتب والمتاجر والفرق والاحتياجات المتكررة.',urgentTitle:'توصيل عاجل',urgentText:'لعمليات التوصيل الحساسة للوقت.',proofTitle:'إثبات التسليم',proofText:'يساعدك تأكيد التسليم على معرفة وقت ومكان استلام الطرد.'},
      coverage:{title:'نطاق التغطية',subtitle:'نيروبي والمناطق المحيطة وفقًا للمسار ومتطلبات الخدمة.',body:'نركز على توصيل المرحلة الأخيرة داخل نيروبي والمناطق القريبة. للمناطق خارج النطاق المعتاد، تواصل معنا قبل الحجز للتأكد من التوفر.'},
      pricing:{title:'الأسعار',subtitle:'عروض أسعار واضحة بلا رسوم مخفية.',body:'يعتمد السعر على المسار والمسافة ومتطلبات الطرد ودرجة الاستعجال وأي معالجة خاصة. اطلب عرضًا قبل الإرسال وسنؤكد المبلغ.',note:'لا رسوم مخفية · تأكيد قبل الإرسال'},
      why:{title:'لماذا لويري',subtitle:'خدمة توصيل مباشرة للأفراد والشركات الذين يقدّرون الموثوقية.',oneTitle:'تواصل واضح',oneText:'نبقيك على اطلاع بحالة الاستلام والإرسال والتسليم.',twoTitle:'تركيز على التسليم في اليوم نفسه',twoText:'نحن مصممون لخدمة توصيل عملية في اليوم نفسه داخل نيروبي.',threeTitle:'إثبات التسليم',threeText:'يتم دعم إتمام الطلب بتأكيد التسليم.',fourTitle:'جاهزون للشركات',fourText:'يمكن تنظيم الاحتياجات المتكررة من خلال حساب للشركات.'},
      pod:{title:'إثبات التسليم',subtitle:'رؤية واضحة من الإرسال حتى التسليم.',body:'نقدم تأكيدًا للتسليم حتى يكون لديك سجل واضح بأن الطرد وصل إلى المستلم المقصود.'},
      rewards:{title:'المكافآت',subtitle:'اكسب نقاطًا كلما استخدمت لويري أكثر.',body:'يمكن للعملاء المؤهلين كسب النقاط وفتح مزايا العضوية بمرور الوقت.',cta:'استكشف المكافآت'},
      faq:{title:'الأسئلة الشائعة',q1:'ما المناطق التي توصلون إليها؟',a1:'نخدم بشكل أساسي نيروبي والمناطق المحيطة. تواصل معنا للتحقق من الموقع قبل الإرسال.',q2:'هل توفرون التوصيل في اليوم نفسه؟',a2:'نعم. التوصيل في اليوم نفسه خدمة أساسية للطرق والحجوزات المؤهلة داخل نيروبي.',q3:'كم تبلغ تكلفة التوصيل؟',a3:'تختلف الأسعار حسب المسار والمسافة والاستعجال ومتطلبات الطرد. نؤكد السعر قبل الإرسال.',q4:'هل يمكن للشركات استخدام لويري للتوصيلات المتكررة؟',a4:'نعم. يمكن للشركات مناقشة الاحتياجات المتكررة وخيارات الحساب المؤسسي.',q5:'كيف أحجز الاستلام؟',a5:'استخدم نموذج الحجز أو واتساب أو بيانات الاتصال الموجودة في الموقع.',q6:'هل يمكنني إرسال أشياء قابلة للكسر أو مستندات مهمة؟',a6:'اذكر ما ترسله عند الحجز حتى نؤكد متطلبات التوصيل.',q7:'كيف أعرف أن التسليم اكتمل؟',a7:'يؤكد إثبات التسليم اكتمال العملية.',q8:'هل يمكنني التواصل مع شخص مباشرة؟',a8:'نعم. استخدم واتساب أو بيانات الاتصال الموجودة في الموقع.'},
      footer:{about:'خدمات توصيل المرحلة الأخيرة والبريد السريع في نيروبي للأفراد والشركات.',links:'روابط سريعة',contact:'اتصل بنا',hours:'ساعات العمل',hoursValue:'الإثنين–الجمعة 08:00–17:00 · السبت 08:00–15:00',rights:'جميع الحقوق محفوظة.'}
    },
    pt: {
      nav:{book:'Agendar recolha',services:'Serviços',pricing:'Preços',business:'Empresas',coverage:'Cobertura',why:'Por que nós',faq:'FAQ',rewards:'Recompensas',careers:'Carreiras',menu:'Menu',where:'Para onde agora',servicesCaption:'O que transportamos e com que rapidez',pricingCaption:'Tarifas cotadas, sem taxas ocultas',businessCaption:'Criar uma conta empresarial',coverageCaption:'Onde entregamos em Nairobi',whyCaption:'O que diferencia a Lueri',faqCaption:'Perguntas comuns, respostas',rewardsCaption:'Ganhe pontos em cada entrega',careersCaption:'Futuras oportunidades na Lueri',bookCaption:'Enviar pedido de recolha'},
      hero:{dispatch:'Expedição / Nairobi e arredores',waybill:'N.º DA GUIA LI–2026',title:'Nós entregamos\npor toda Nairobi\nhoje.',subtitle:'A Lueri International gere entregas de última milha e serviços de estafeta para particulares e empresas — encomendas, documentos e pedidos de comércio eletrónico, recolhidos e entregues no mesmo dia em Nairobi.',scope:'Última milha em Nairobi · Sem transporte transfronteiriço',stamp:'Entrega no mesmo dia',pickup:'RECOLHA',dropoff:'ENTREGA',bookBtn:'Agendar recolha',whatsappBtn:'Contactar no WhatsApp'},
      booking:{heading:'Agendar uma entrega',intro:'Diga-nos o que precisa de enviar e para onde deve ir. Confirmaremos consigo os detalhes da expedição.',pickup:'Local de recolha',pickupPlaceholder:'Introduza o local de recolha',dropoff:'Local de entrega',dropoffPlaceholder:'Introduza o destino',name:'O seu nome',namePlaceholder:'Introduza o seu nome completo',phone:'Número de telefone',phonePlaceholder:'ex. 0712 345 678',email:'Endereço de email',emailPlaceholder:'you@example.com',item:'O que está a enviar?',itemPlaceholder:'Encomenda, documento, presente, etc.',notes:'Notas adicionais',notesPlaceholder:'Instruções especiais, ponto de referência, dados do destinatário…',submit:'Solicitar recolha',submitting:'A enviar pedido…',success:'Pedido recebido',successCopy:'A abrir o WhatsApp para confirmar a expedição…',openWhatsapp:'Abrir WhatsApp',close:'Fechar'},
      common:{learnMore:'Saiba mais',getQuote:'Pedir orçamento',sameDay:'Entrega no mesmo dia',secure:'Seguro e fiável',support:'Apoio ao cliente'},
      services:{title:'Serviços',subtitle:'Serviços de entrega práticos centrados em rapidez, fiabilidade e comunicação clara.',parcelTitle:'Entrega de encomendas e documentos',parcelText:'Entrega ponto a ponto em Nairobi para particulares — encomendas, documentos, presentes e recados pessoais.',ecommerceTitle:'Entregas de comércio eletrónico',ecommerceText:'Última milha para vendedores online, incluindo recolha, expedição e entrega ao cliente.',businessTitle:'Entregas empresariais e corporativas',businessText:'Entregas programadas e a pedido para escritórios, lojas, equipas e necessidades recorrentes.',urgentTitle:'Expedição urgente',urgentText:'Para entregas sensíveis ao tempo.',proofTitle:'Comprovativo de entrega',proofText:'A confirmação de entrega permite saber quando e onde o artigo foi recebido.'},
      coverage:{title:'Cobertura',subtitle:'Nairobi e arredores, de acordo com a rota e os requisitos do serviço.',body:'Concentramo-nos na entrega de última milha em Nairobi e áreas próximas. Para locais fora da área habitual, contacte-nos antes de reservar.'},
      pricing:{title:'Preços',subtitle:'Orçamentos claros, sem taxas ocultas.',body:'O preço depende da rota, distância, requisitos da encomenda, urgência e manuseamento especial. Peça um orçamento antes da expedição.',note:'Sem taxas ocultas · Confirmado antes da expedição'},
      why:{title:'Por que Lueri',subtitle:'Um serviço de entrega direto para pessoas e empresas que valorizam a fiabilidade.',oneTitle:'Comunicação clara',oneText:'Mantemo-lo informado sobre recolha, expedição e entrega.',twoTitle:'Foco no mesmo dia',twoText:'Estamos construídos para entregas práticas no mesmo dia em Nairobi.',threeTitle:'Comprovativo de entrega',threeText:'A conclusão é apoiada por confirmação da entrega.',fourTitle:'Pronto para empresas',fourText:'As necessidades recorrentes podem ser organizadas através de uma conta empresarial.'},
      pod:{title:'Comprovativo de entrega',subtitle:'Visibilidade desde a expedição até à entrega.',body:'Fornecemos confirmação para que tenha um registo claro de que o artigo chegou ao destinatário previsto.'},
      rewards:{title:'Recompensas',subtitle:'Ganhe pontos à medida que faz mais entregas com a Lueri.',body:'Clientes elegíveis podem ganhar pontos e desbloquear benefícios de membro ao longo do tempo.',cta:'Explorar recompensas'},
      faq:{title:'Perguntas frequentes',q1:'Para que áreas fazem entregas?',a1:'Servimos principalmente Nairobi e arredores. Contacte-nos para confirmar um local específico.',q2:'Oferecem entrega no mesmo dia?',a2:'Sim. A entrega no mesmo dia é um serviço central para rotas e reservas elegíveis em Nairobi.',q3:'Quanto custa uma entrega?',a3:'A tarifa depende da rota, distância, urgência e requisitos da encomenda. O orçamento é confirmado antes da expedição.',q4:'As empresas podem usar a Lueri para entregas recorrentes?',a4:'Sim. Podemos discutir necessidades recorrentes e opções de conta empresarial.',q5:'Como agendo uma recolha?',a5:'Use o formulário, WhatsApp ou os contactos indicados no site.',q6:'Posso enviar artigos frágeis ou documentos importantes?',a6:'Indique o que está a enviar para que possamos confirmar os requisitos da expedição.',q7:'Como sei que a entrega foi concluída?',a7:'A confirmação da entrega comprova a conclusão.',q8:'Posso falar diretamente com alguém?',a8:'Sim. Use o WhatsApp ou os contactos do site.'},
      footer:{about:'Entrega de última milha e serviço de estafeta em Nairobi para particulares e empresas.',links:'Links rápidos',contact:'Contacto',hours:'Horário',hoursValue:'Seg–Sex 08:00–17:00 · Sáb 08:00–15:00',rights:'Todos os direitos reservados.'}
    }
  };

  function getPath(obj, path) {
    return path.split('.').reduce((acc, key) => acc && acc[key], obj);
  }

  function setLanguage(lang) {
    const code = LANGS.includes(lang) ? lang : 'en';
    const dict = translations[code] || translations.en;
    document.documentElement.lang = code;
    document.body.classList.toggle('rtl', code === 'ar');
    document.documentElement.dir = code === 'ar' ? 'rtl' : 'ltr';

    document.querySelectorAll('[data-i18n]').forEach((el) => {
      const value = getPath(dict, el.getAttribute('data-i18n')) || getPath(translations.en, el.getAttribute('data-i18n'));
      if (value == null) return;
      el.textContent = value;
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach((el) => {
      const key = el.getAttribute('data-i18n-placeholder');
      const value = getPath(dict, key) || getPath(translations.en, key);
      if (value != null) el.setAttribute('placeholder', value);
    });

    document.querySelectorAll('[data-i18n-aria]').forEach((el) => {
      const key = el.getAttribute('data-i18n-aria');
      const value = getPath(dict, key) || getPath(translations.en, key);
      if (value != null) el.setAttribute('aria-label', value);
    });

    const selector = document.getElementById('languageSelector');
    if (selector) selector.value = code;
    try { localStorage.setItem(STORAGE_KEY, code); } catch (_) {}
    window.dispatchEvent(new CustomEvent('lueri:languagechange', { detail: { language: code } }));
  }

  function init() {
    const selector = document.getElementById('languageSelector');
    if (selector) selector.addEventListener('change', (e) => setLanguage(e.target.value));

    let saved = 'en';
    try { saved = localStorage.getItem(STORAGE_KEY) || 'en'; } catch (_) {}
    setLanguage(saved);
  }

  window.LueriI18n = { init, setLanguage, translations, languages: LANGS };
  document.addEventListener('DOMContentLoaded', init, { once: true });
})();
