/* Lueri International localization + Lucy visual integration */
(function(){'use strict';
const LANGS={en:'English',sw:'Kiswahili',fr:'Français',es:'Español',ar:'العربية',pt:'Português',zh:'中文'};
const CODES={en:'en',sw:'sw',fr:'fr',es:'es',ar:'ar',pt:'pt',zh:'zh-CN'};
const RTL=new Set(['ar']); const KEY='lueri-language'; let ready=false,pending=null;
function get(){try{const v=localStorage.getItem(KEY)||localStorage.getItem('lueri_lang');return LANGS[v]?v:'en'}catch(_){return'en'}}
function save(v){try{localStorage.setItem(KEY,v);localStorage.setItem('lueri_lang',v)}catch(_) {}}
function doc(v){if(!LANGS[v])v='en';document.documentElement.lang=v==='zh'?'zh-CN':v;document.documentElement.dir=RTL.has(v)?'rtl':'ltr';document.documentElement.dataset.lueriLanguage=v;document.querySelectorAll('[data-lueri-language]').forEach(e=>e.value=v)}
function cookie(v){const x=`/en/${CODES[v]||'en'}`;try{document.cookie=`googtrans=${x}; path=/; SameSite=Lax`;document.cookie=`googtrans=${x}; path=/; domain=${location.hostname}; SameSite=Lax`}catch(_) {}}
function clearCookie(){try{['googtrans','googtransopt'].forEach(n=>{document.cookie=`${n}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/`;document.cookie=`${n}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; domain=${location.hostname}`})}catch(_) {}}
function styles(){if(document.getElementById('lueri-i18n-style'))return;const s=document.createElement('style');s.id='lueri-i18n-style';s.textContent=`.goog-te-banner-frame.skiptranslate,body>.skiptranslate,.goog-te-gadget,.goog-logo-link,.goog-te-balloon-frame{display:none!important}body{top:0!important}html.translated-ltr,html.translated-rtl{margin-top:0!important}.lueri-language-picker{display:flex;align-items:center;margin-left:8px;position:relative;z-index:10000}.lueri-language-picker select{font:500 12px/1.2 'IBM Plex Sans',sans-serif;border:1px solid currentColor;border-radius:3px;background:#1b2620;color:#f0ead8;padding:9px 30px 9px 10px;min-height:38px;min-width:122px;cursor:pointer;color-scheme:dark}.lueri-language-picker select option{background:#1b2620;color:#f0ead8}.lueri-lucy-avatar{width:40px;height:40px;flex:0 0 40px;border-radius:50%;display:block;object-fit:cover;box-shadow:0 2px 8px rgba(0,0,0,.18)}#lucy-launcher .lueri-lucy-avatar{width:28px;height:28px;flex-basis:28px}@media(max-width:640px){.lueri-language-picker{margin-left:4px}.lueri-language-picker select{max-width:122px;min-width:112px;padding:8px 20px 8px 7px;font-size:11px}}`;document.head.appendChild(s)}
function picker(){if(document.querySelector('.lueri-language-picker'))return;const w=document.createElement('div');w.className='lueri-language-picker notranslate';w.setAttribute('translate','no');w.setAttribute('aria-label','Language selector');const q=document.createElement('select');q.setAttribute('data-lueri-language','');q.setAttribute('aria-label','Language');q.className='notranslate';Object.entries(LANGS).forEach(([c,n])=>{const o=document.createElement('option');o.value=c;o.textContent=n;o.setAttribute('translate','no');q.appendChild(o)});q.addEventListener('change',e=>set(e.target.value,true));w.appendChild(q);const host=document.querySelector('.nav-controls')||document.querySelector('.navbar>div:last-child')||document.querySelector('header nav,.site-header nav,.header-nav,.nav-links');if(host)host.appendChild(w);else document.body.appendChild(w)}
function combo(){return document.querySelector('.goog-te-combo')}
function apply(v){const c=combo();if(!c){pending=v;return false}const x=CODES[v]||'en';if(c.value!==x){c.value=x;c.dispatchEvent(new Event('change',{bubbles:true}))}doc(v);pending=null;return true}
function set(v,user){if(!LANGS[v])return;save(v);doc(v);cookie(v);if(user){window.location.reload();return}if(v==='en')clearCookie();apply(v)}
function install(){if(window.google&&window.google.translate&&window.google.translate.TranslateElement){initGoogle();return}if(document.getElementById('lueri-google-translate-script'))return;window.googleTranslateElementInit=initGoogle;const s=document.createElement('script');s.id='lueri-google-translate-script';s.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';s.async=true;s.defer=true;document.head.appendChild(s)}
function initGoogle(){if(ready)return;try{new google.translate.TranslateElement({pageLanguage:'en',includedLanguages:'sw,fr,es,ar,pt,zh-CN',autoDisplay:false,multilanguagePage:true},'lueri-google-translate');ready=true;const v=pending||get();doc(v);[250,1000,2500].forEach(ms=>setTimeout(()=>apply(v),ms))}catch(e){console.error('Lueri language engine failed:',e)}}
function googleHost(){if(document.getElementById('lueri-google-translate'))return;const d=document.createElement('div');d.id='lueri-google-translate';d.className='notranslate';d.setAttribute('translate','no');d.setAttribute('aria-hidden','true');d.style.cssText='position:absolute;width:1px;height:1px;overflow:hidden;opacity:0;pointer-events:none;left:-99999px;top:-99999px';document.body.appendChild(d)}
function lucyAvatar(){styles();const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120"><circle cx="60" cy="60" r="58" fill="#e8b93d"/><path d="M25 48c2-22 18-36 35-36 20 0 35 15 36 38-7-9-17-14-31-14-14 0-27 5-40 12z" fill="#1b2620"/><circle cx="42" cy="56" r="5" fill="#1b2620"/><circle cx="78" cy="56" r="5" fill="#1b2620"/><path d="M42 76c10 8 26 8 36 0" fill="none" stroke="#1b2620" stroke-width="5" stroke-linecap="round"/><path d="M28 106c6-18 18-27 32-27s26 9 32 27" fill="#274238"/><circle cx="60" cy="60" r="56" fill="none" stroke="#1b2620" stroke-width="3"/></svg>';const src='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg);function mount(){document.querySelectorAll('.lucy-avatar').forEach(h=>{if(h.querySelector('.lueri-lucy-avatar'))return;h.textContent='';const i=document.createElement('img');i.className='lueri-lucy-avatar';i.src=src;i.alt='Lucy';h.appendChild(i)});const l=document.getElementById('lucy-launcher');if(l&&!l.querySelector('.lueri-lucy-avatar')){const i=document.createElement('img');i.className='lueri-lucy-avatar';i.src=src;i.alt='';l.insertBefore(i,l.firstChild)}}const o=new MutationObserver(mount);o.observe(document.body,{childList:true,subtree:true});mount();[300,1000,2500].forEach(ms=>setTimeout(mount,ms))}
function init(){styles();picker();googleHost();const v=get();save(v);cookie(v);doc(v);install();lucyAvatar()}
window.LueriI18n={languages:LANGS,get:get,set:set,apply:set,init:init};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();