/* Lueri International localization + Lucy visual integration */
(function(){'use strict';
const LANGS={en:'English',sw:'Kiswahili',fr:'Français',es:'Español',ar:'العربية',pt:'Português',zh:'中文'};
const CODES={en:'en',sw:'sw',fr:'fr',es:'es',ar:'ar',pt:'pt',zh:'zh-CN'};
const RTL=new Set(['ar']); const KEY='lueri-language'; let ready=false,pending=null;
function get(){try{const v=localStorage.getItem(KEY)||localStorage.getItem('lueri_lang')||localStorage.getItem('lueri_locale');return LANGS[v]?v:'en'}catch(_){return'en'}}
function save(v){try{localStorage.setItem(KEY,v);localStorage.setItem('lueri_lang',v);localStorage.setItem('lueri_locale',v)}catch(_) {}}
function doc(v){if(!LANGS[v])v='en';document.documentElement.lang=v==='zh'?'zh-CN':v;document.documentElement.dir=RTL.has(v)?'rtl':'ltr';document.documentElement.dataset.lueriLanguage=v;document.querySelectorAll('[data-lueri-language]').forEach(e=>e.value=v)}
function cookie(v){const x=`/en/${CODES[v]||'en'}`;try{document.cookie=`googtrans=${x}; path=/; SameSite=Lax`;document.cookie=`googtrans=${x}; path=/; domain=${location.hostname}; SameSite=Lax`}catch(_) {}}
function clearCookie(){try{['googtrans','googtransopt'].forEach(n=>{document.cookie=`${n}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/`;document.cookie=`${n}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; domain=${location.hostname}`})}catch(_) {}}
function styles(){if(document.getElementById('lueri-i18n-style'))return;const s=document.createElement('style');s.id='lueri-i18n-style';s.textContent=`
.goog-te-banner-frame,.goog-te-menu-frame,.goog-te-gadget,.goog-te-spinner-pos,.goog-te-spinner,.goog-te-balloon-frame,body>.skiptranslate,iframe.skiptranslate,#google_translate_element,.goog-logo-link,.goog-power-badge,.goog-te-menu-value,.VIpgJd-ZVi9od-aZ2wEe-wOHMyf{display:none!important;visibility:hidden!important;opacity:0!important;height:0!important;width:0!important;overflow:hidden!important;pointer-events:none!important}
body{top:0!important;position:relative!important}
html.translated-ltr,html.translated-rtl{margin-top:0!important}
.lueri-language-picker{display:flex;align-items:center;margin-left:8px;position:relative;z-index:10000}
.lueri-language-picker select{font:500 12px/1.2 'IBM Plex Sans',sans-serif;border:1px solid currentColor;border-radius:3px;background:#1b2620;color:#f0ead8;padding:9px 30px 9px 10px;min-height:38px;min-width:122px;cursor:pointer;color-scheme:dark}
.lueri-language-picker select option{background:#1b2620;color:#f0ead8}
@media(max-width:640px){.lueri-language-picker{margin-left:4px}.lueri-language-picker select{max-width:122px;min-width:112px;padding:8px 20px 8px 7px;font-size:11px}}
`;document.head.appendChild(s)}
function picker(){if(document.querySelector('.lueri-language-picker'))return;const w=document.createElement('div');w.className='lueri-language-picker notranslate';w.setAttribute('translate','no');w.setAttribute('aria-label','Language selector');const q=document.createElement('select');q.setAttribute('data-lueri-language','');q.setAttribute('aria-label','Language');q.className='notranslate';Object.entries(LANGS).forEach(([c,n])=>{const o=document.createElement('option');o.value=c;o.textContent=n;o.setAttribute('translate','no');q.appendChild(o)});q.addEventListener('change',e=>set(e.target.value,true));w.appendChild(q);const host=document.querySelector('.nav-controls')||document.querySelector('.navbar>div:last-child')||document.querySelector('header nav,.site-header nav,.header-nav,.nav-links');if(host)host.appendChild(w);else document.body.appendChild(w)}
function combo(){return document.querySelector('.goog-te-combo')}
function apply(v){const c=combo();if(!c){pending=v;return false}const x=CODES[v]||'en';if(c.value!==x){c.value=x;c.dispatchEvent(new Event('change',{bubbles:true}))}doc(v);pending=null;return true}
function announce(v){window.dispatchEvent(new CustomEvent('lueri-language-change',{detail:{locale:v}}));document.dispatchEvent(new CustomEvent('lueri-language-change',{detail:{locale:v}}))}
function set(v,user){if(!LANGS[v])return;save(v);doc(v);if(v==='en'){clearCookie();pending='en';announce('en');if(user)window.location.reload();else apply('en');return}cookie(v);pending=v;announce(v);apply(v);if(user){[250,750,1500,2500].forEach(ms=>setTimeout(()=>apply(v),ms))}}
function install(){if(window.google&&window.google.translate&&window.google.translate.TranslateElement){initGoogle();return}if(document.getElementById('lueri-google-translate-script'))return;window.googleTranslateElementInit=initGoogle;const s=document.createElement('script');s.id='lueri-google-translate-script';s.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';s.async=true;s.defer=true;document.head.appendChild(s)}
function initGoogle(){if(ready)return;try{new google.translate.TranslateElement({pageLanguage:'en',includedLanguages:'sw,fr,es,ar,pt,zh-CN',autoDisplay:false,multilanguagePage:true},'lueri-google-translate');ready=true;const v=pending||get();doc(v);if(v==='en')clearCookie();[250,1000,2500].forEach(ms=>setTimeout(()=>apply(v),ms))}catch(e){console.error('Lueri language engine failed:',e)}}
function linkifyLucyMessages(){document.querySelectorAll('.lucy-message.bot').forEach(el=>{if(el.dataset.lucyLinksReady==='1')return;const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);const nodes=[];let n;while(n=walker.nextNode())if(/https?:\/\/|www\./i.test(n.nodeValue||''))nodes.push(n);nodes.forEach(textNode=>{const text=textNode.nodeValue||'',frag=document.createDocumentFragment(),re=/(https?:\/\/[^\s<]+|www\.[^\s<]+)/gi;let last=0,m;while(m=re.exec(text)){if(m.index>last)frag.appendChild(document.createTextNode(text.slice(last,m.index)));const raw=m[0],trail=/[.,!?;:)]$/.test(raw)?raw.slice(-1):'',url=trail?raw.slice(0,-1):raw,a=document.createElement('a');a.href=url.startsWith('www.')?'https://'+url:url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=url;a.style.textDecoration='underline';a.style.fontWeight='700';frag.appendChild(a);if(trail)frag.appendChild(document.createTextNode(trail));last=m.index+raw.length}if(last<text.length)frag.appendChild(document.createTextNode(text.slice(last)));textNode.parentNode.replaceChild(frag,textNode)});el.dataset.lucyLinksReady='1'})}
function googleHost(){if(document.getElementById('lueri-google-translate'))return;const d=document.createElement('div');d.id='lueri-google-translate';d.className='notranslate';d.setAttribute('translate','no');d.setAttribute('aria-hidden','true');d.style.cssText='position:absolute;width:1px;height:1px;overflow:hidden;opacity:0;pointer-events:none;left:-99999px;top:-99999px';document.body.appendChild(d)}
function init(){styles();picker();googleHost();linkifyLucyMessages();const o=new MutationObserver(linkifyLucyMessages);o.observe(document.body,{childList:true,subtree:true});const v=get();save(v);doc(v);if(v==='en')clearCookie();else cookie(v);pending=v;install()}
window.LueriI18n={languages:LANGS,get:get,set:set,apply:set,init:init};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();